/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.domesticsearchflightproduct.v1;

import com.ctrip.soa.global.api.comm.head.v1.Head;
import com.ctrip.soa.global.api.flightcommon.v1.GaCabinClassType;
import com.ctrip.soa.global.api.flightcommon.v1.GaFlightWayType;
import com.ctrip.soa.global.api.flightcommon.v1.PaginationInfo;
import com.ctrip.soa.global.api.flightcommon.v1.ProductKeyInfo;
import com.ctrip.soa.global.api.flightcommon.v1.SegmentParameterInfo;
import com.ctrip.soa.global.api.flightcommon.v1.TravelerInfo;
import com.ctrip.soa.global.api.searhflightporduct.v1.FilterInfo;
import com.ctrip.soa.global.api.searhflightporduct.v1.SequenceInfo;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "DomesticSearchFlightProductRequest", namespace = "http://soa.ctrip.com/Global/API/DomesticSearchFlightProduct/v1")
@XmlType(name = "DomesticSearchFlightProductRequest", propOrder = {
    "head",
    "tripType",
    "classType",
    "travelerNumber",
    "segmentParameterList",
    "filterInfo",
    "sequenceInfo",
    "productKeyInfo",
    "paginationInfo"
})
@SuppressWarnings("all")
public class DomesticSearchFlightProductRequest  {

    private static final long serialVersionUID = 1L;

    public DomesticSearchFlightProductRequest(
        Head head, 
        GaFlightWayType tripType, 
        GaCabinClassType classType, 
        TravelerInfo travelerNumber, 
        List<SegmentParameterInfo> segmentParameterList, 
        FilterInfo filterInfo, 
        SequenceInfo sequenceInfo, 
        ProductKeyInfo productKeyInfo, 
        PaginationInfo paginationInfo) {
        this.head = head;
        this.tripType = tripType;
        this.classType = classType;
        this.travelerNumber = travelerNumber;
        this.segmentParameterList = segmentParameterList;
        this.filterInfo = filterInfo;
        this.sequenceInfo = sequenceInfo;
        this.productKeyInfo = productKeyInfo;
        this.paginationInfo = paginationInfo;
    }

    public DomesticSearchFlightProductRequest() {
    }

    @JsonProperty("Head")
    @XmlElement(name = "Head")
    private Head head;

    @FieldDoc("航程类型")
    @JsonProperty("TripType")
    @XmlElement(name = "TripType")
    private GaFlightWayType tripType;

    @FieldDoc("航程类型")
    @JsonProperty("ClassType")
    @XmlElement(name = "ClassType")
    private GaCabinClassType classType;

    @FieldDoc("乘客人数")
    @JsonProperty("TravelerNumber")
    @XmlElement(name = "TravelerNumber")
    private TravelerInfo travelerNumber;

    @FieldDoc("航段信息")
    @JsonProperty("SegmentParameterList")
    @XmlElement(name = "SegmentParameterList")
    private List<SegmentParameterInfo> segmentParameterList;

    @FieldDoc("航段信息")
    @JsonProperty("FilterInfo")
    @XmlElement(name = "FilterInfo")
    private FilterInfo filterInfo;

    @FieldDoc("排序信息")
    @JsonProperty("SequenceInfo")
    @XmlElement(name = "SequenceInfo")
    private SequenceInfo sequenceInfo;

    @FieldDoc("定位产品的关键参数，响应中返回")
    @JsonProperty("ProductKeyInfo")
    @XmlElement(name = "ProductKeyInfo")
    private ProductKeyInfo productKeyInfo;

    @FieldDoc("分页参数")
    @JsonProperty("PaginationInfo")
    @XmlElement(name = "PaginationInfo", nillable = true)
    private PaginationInfo paginationInfo;

    public Head getHead() {
        return this.head;
    }

    public void setHead(Head head) {
        this.head = head;
    }

    /**
     * 航程类型
     */
    public GaFlightWayType getTripType() {
        return this.tripType;
    }

    public void setTripType(GaFlightWayType tripType) {
        this.tripType = tripType;
    }

    /**
     * 航程类型
     */
    public GaCabinClassType getClassType() {
        return this.classType;
    }

    public void setClassType(GaCabinClassType classType) {
        this.classType = classType;
    }

    /**
     * 乘客人数
     */
    public TravelerInfo getTravelerNumber() {
        return this.travelerNumber;
    }

    public void setTravelerNumber(TravelerInfo travelerNumber) {
        this.travelerNumber = travelerNumber;
    }

    /**
     * 航段信息
     */
    public List<SegmentParameterInfo> getSegmentParameterList() {
        return this.segmentParameterList;
    }

    public void setSegmentParameterList(List<SegmentParameterInfo> segmentParameterList) {
        this.segmentParameterList = segmentParameterList;
    }

    /**
     * 航段信息
     */
    public FilterInfo getFilterInfo() {
        return this.filterInfo;
    }

    public void setFilterInfo(FilterInfo filterInfo) {
        this.filterInfo = filterInfo;
    }

    /**
     * 排序信息
     */
    public SequenceInfo getSequenceInfo() {
        return this.sequenceInfo;
    }

    public void setSequenceInfo(SequenceInfo sequenceInfo) {
        this.sequenceInfo = sequenceInfo;
    }

    /**
     * 定位产品的关键参数，响应中返回
     */
    public ProductKeyInfo getProductKeyInfo() {
        return this.productKeyInfo;
    }

    public void setProductKeyInfo(ProductKeyInfo productKeyInfo) {
        this.productKeyInfo = productKeyInfo;
    }

    /**
     * 分页参数
     */
    public PaginationInfo getPaginationInfo() {
        return this.paginationInfo;
    }

    public void setPaginationInfo(PaginationInfo paginationInfo) {
        this.paginationInfo = paginationInfo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final DomesticSearchFlightProductRequest other = (DomesticSearchFlightProductRequest)obj;
        return
            Objects.equal(this.head, other.head) && 
            Objects.equal(this.tripType, other.tripType) && 
            Objects.equal(this.classType, other.classType) && 
            Objects.equal(this.travelerNumber, other.travelerNumber) && 
            Objects.equal(this.segmentParameterList, other.segmentParameterList) && 
            Objects.equal(this.filterInfo, other.filterInfo) && 
            Objects.equal(this.sequenceInfo, other.sequenceInfo) && 
            Objects.equal(this.productKeyInfo, other.productKeyInfo) && 
            Objects.equal(this.paginationInfo, other.paginationInfo);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.head);
        result = 31 * result + Objects.hashCode(this.tripType);
        result = 31 * result + Objects.hashCode(this.classType);
        result = 31 * result + Objects.hashCode(this.travelerNumber);
        result = 31 * result + Objects.hashCode(this.segmentParameterList);
        result = 31 * result + Objects.hashCode(this.filterInfo);
        result = 31 * result + Objects.hashCode(this.sequenceInfo);
        result = 31 * result + Objects.hashCode(this.productKeyInfo);
        result = 31 * result + Objects.hashCode(this.paginationInfo);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("head", head)
            .add("tripType", tripType)
            .add("classType", classType)
            .add("travelerNumber", travelerNumber)
            .add("segmentParameterList", segmentParameterList)
            .add("filterInfo", filterInfo)
            .add("sequenceInfo", sequenceInfo)
            .add("productKeyInfo", productKeyInfo)
            .add("paginationInfo", paginationInfo)
            .toString();
    }
}