/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.garescheduleverify.v1;

import com.ctrip.soa.global.api.comm.responsehead.v1.ResponseHead;
import com.ctrip.soa.global.api.flightcommon.v1.GaPriceChangeInfo;
import com.ctrip.soa.global.api.flightcommon.v1.GaReshedulePriceInfo;
import com.ctrip.soa.global.api.flightcommon.v1.GaVerifyStatus;
import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 机票改签验舱验价接口返回
 */
@DtoDoc("机票改签验舱验价接口返回")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GaRescheduleVerifyResponse", namespace = "http://soa.ctrip.com/Global/API/GaRescheduleVerify/v1")
@XmlType(name = "GaRescheduleVerifyResponse", propOrder = {
    "responseStatus",
    "responseHead",
    "verifyTokenNumber",
    "verifyStatus",
    "priceChangeInfo",
    "reshedulePriceInfo",
    "rescheduleVerifyResult"
})
@SuppressWarnings("all")
public class GaRescheduleVerifyResponse implements HasResponseStatus {

    private static final long serialVersionUID = 1L;

    public GaRescheduleVerifyResponse(
        ResponseStatusType responseStatus, 
        ResponseHead responseHead, 
        String verifyTokenNumber, 
        GaVerifyStatus verifyStatus, 
        GaPriceChangeInfo priceChangeInfo, 
        GaReshedulePriceInfo reshedulePriceInfo, 
        int rescheduleVerifyResult) {
        this.responseStatus = responseStatus;
        this.responseHead = responseHead;
        this.verifyTokenNumber = verifyTokenNumber;
        this.verifyStatus = verifyStatus;
        this.priceChangeInfo = priceChangeInfo;
        this.reshedulePriceInfo = reshedulePriceInfo;
        this.rescheduleVerifyResult = rescheduleVerifyResult;
    }

    public GaRescheduleVerifyResponse() {
    }

    @FieldDoc("SOA2.0返回头部信息")
    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @FieldDoc("IBU返回头部信息")
    @JsonProperty("ResponseHead")
    @XmlElement(name = "ResponseHead")
    private ResponseHead responseHead;

    @FieldDoc("异步调用时，返回的Token")
    @JsonProperty("VerifyTokenNumber")
    @XmlElement(name = "VerifyTokenNumber")
    private String verifyTokenNumber;

    @FieldDoc("异步调用时，返回的Token")
    @JsonProperty("VerifyStatus")
    @XmlElement(name = "VerifyStatus")
    private GaVerifyStatus verifyStatus;

    @FieldDoc("变价信息")
    @JsonProperty("PriceChangeInfo")
    @XmlElement(name = "PriceChangeInfo")
    private GaPriceChangeInfo priceChangeInfo;

    @FieldDoc("改签价格信息")
    @JsonProperty("ReshedulePriceInfo")
    @XmlElement(name = "ReshedulePriceInfo")
    private GaReshedulePriceInfo reshedulePriceInfo;

    @FieldDoc("改签验证结果:" +
            "0-不可提交改签申请，也不可提交支付" +
            "1-可以提交支付  提交改签申请" +
            "2-不可以支付 可以提交改签申请")
    @JsonProperty("RescheduleVerifyResult")
    @XmlElement(name = "RescheduleVerifyResult")
    private int rescheduleVerifyResult;

    /**
     * SOA2.0返回头部信息
     */
    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * IBU返回头部信息
     */
    public ResponseHead getResponseHead() {
        return this.responseHead;
    }

    public void setResponseHead(ResponseHead responseHead) {
        this.responseHead = responseHead;
    }

    /**
     * 异步调用时，返回的Token
     */
    public String getVerifyTokenNumber() {
        return this.verifyTokenNumber;
    }

    public void setVerifyTokenNumber(String verifyTokenNumber) {
        this.verifyTokenNumber = verifyTokenNumber;
    }

    /**
     * 异步调用时，返回的Token
     */
    public GaVerifyStatus getVerifyStatus() {
        return this.verifyStatus;
    }

    public void setVerifyStatus(GaVerifyStatus verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * 变价信息
     */
    public GaPriceChangeInfo getPriceChangeInfo() {
        return this.priceChangeInfo;
    }

    public void setPriceChangeInfo(GaPriceChangeInfo priceChangeInfo) {
        this.priceChangeInfo = priceChangeInfo;
    }

    /**
     * 改签价格信息
     */
    public GaReshedulePriceInfo getReshedulePriceInfo() {
        return this.reshedulePriceInfo;
    }

    public void setReshedulePriceInfo(GaReshedulePriceInfo reshedulePriceInfo) {
        this.reshedulePriceInfo = reshedulePriceInfo;
    }

    /**
     * 改签验证结果:
     *             0-不可提交改签申请，也不可提交支付
     *             1-可以提交支付  提交改签申请
     *             2-不可以支付 可以提交改签申请
     */
    public int getRescheduleVerifyResult() {
        return this.rescheduleVerifyResult;
    }

    public void setRescheduleVerifyResult(int rescheduleVerifyResult) {
        this.rescheduleVerifyResult = rescheduleVerifyResult;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GaRescheduleVerifyResponse other = (GaRescheduleVerifyResponse)obj;
        return
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.responseHead, other.responseHead) && 
            Objects.equal(this.verifyTokenNumber, other.verifyTokenNumber) && 
            Objects.equal(this.verifyStatus, other.verifyStatus) && 
            Objects.equal(this.priceChangeInfo, other.priceChangeInfo) && 
            Objects.equal(this.reshedulePriceInfo, other.reshedulePriceInfo) && 
            Objects.equal(this.rescheduleVerifyResult, other.rescheduleVerifyResult);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.responseHead);
        result = 31 * result + Objects.hashCode(this.verifyTokenNumber);
        result = 31 * result + Objects.hashCode(this.verifyStatus);
        result = 31 * result + Objects.hashCode(this.priceChangeInfo);
        result = 31 * result + Objects.hashCode(this.reshedulePriceInfo);
        result = 31 * result + Objects.hashCode(this.rescheduleVerifyResult);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseStatus", responseStatus)
            .add("responseHead", responseHead)
            .add("verifyTokenNumber", verifyTokenNumber)
            .add("verifyStatus", verifyStatus)
            .add("priceChangeInfo", priceChangeInfo)
            .add("reshedulePriceInfo", reshedulePriceInfo)
            .add("rescheduleVerifyResult", rescheduleVerifyResult)
            .toString();
    }
}