/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.getmulticurrencycoupon.v1;

import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiCurrencyCouponInfo", propOrder = {
    "couponCode",
    "couponType",
    "startDate",
    "endDate",
    "currency",
    "airlines",
    "couponSaleTypes",
    "isAirlineWildCard",
    "strategy"
})
@SuppressWarnings("all")
public class MultiCurrencyCouponInfo  {

    private static final long serialVersionUID = 1L;

    public MultiCurrencyCouponInfo(
        String couponCode, 
        String couponType, 
        long startDate, 
        long endDate, 
        String currency, 
        List<String> airlines, 
        List<String> couponSaleTypes, 
        boolean isAirlineWildCard, 
        MultiCurrencyCouponStrategyType strategy) {
        this.couponCode = couponCode;
        this.couponType = couponType;
        this.startDate = startDate;
        this.endDate = endDate;
        this.currency = currency;
        this.airlines = airlines;
        this.couponSaleTypes = couponSaleTypes;
        this.isAirlineWildCard = isAirlineWildCard;
        this.strategy = strategy;
    }

    public MultiCurrencyCouponInfo() {
    }

    @FieldDoc("优惠券代码")
    @JsonProperty("CouponCode")
    @XmlElement(name = "CouponCode")
    private String couponCode;

    @FieldDoc("优惠券代码")
    @JsonProperty("CouponType")
    @XmlElement(name = "CouponType")
    private String couponType;

    @FieldDoc("有效期开始时间")
    @JsonProperty("StartDate")
    @XmlElement(name = "StartDate")
    private long startDate;

    @FieldDoc("有效期到期时间")
    @JsonProperty("EndDate")
    @XmlElement(name = "EndDate")
    private long endDate;

    @FieldDoc("币种")
    @JsonProperty("Currency")
    @XmlElement(name = "Currency")
    private String currency;

    @FieldDoc("航司")
    @JsonProperty("Airlines")
    @XmlElement(name = "Airlines")
    private List<String> airlines;

    @FieldDoc("CouponSaleType")
    @JsonProperty("CouponSaleTypes")
    @XmlElement(name = "CouponSaleTypes")
    private List<String> couponSaleTypes;

    @FieldDoc("IsAirlineWildCard")
    @JsonProperty("IsAirlineWildCard")
    @XmlElement(name = "IsAirlineWildCard")
    private boolean isAirlineWildCard;

    @FieldDoc("CouponSaleType")
    @JsonProperty("Strategy")
    @XmlElement(name = "Strategy")
    private MultiCurrencyCouponStrategyType strategy;

    /**
     * 优惠券代码
     */
    public String getCouponCode() {
        return this.couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    /**
     * 优惠券代码
     */
    public String getCouponType() {
        return this.couponType;
    }

    public void setCouponType(String couponType) {
        this.couponType = couponType;
    }

    /**
     * 有效期开始时间
     */
    public long getStartDate() {
        return this.startDate;
    }

    public void setStartDate(long startDate) {
        this.startDate = startDate;
    }

    /**
     * 有效期到期时间
     */
    public long getEndDate() {
        return this.endDate;
    }

    public void setEndDate(long endDate) {
        this.endDate = endDate;
    }

    /**
     * 币种
     */
    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * 航司
     */
    public List<String> getAirlines() {
        return this.airlines;
    }

    public void setAirlines(List<String> airlines) {
        this.airlines = airlines;
    }

    /**
     * CouponSaleType
     */
    public List<String> getCouponSaleTypes() {
        return this.couponSaleTypes;
    }

    public void setCouponSaleTypes(List<String> couponSaleTypes) {
        this.couponSaleTypes = couponSaleTypes;
    }

    /**
     * IsAirlineWildCard
     */
    public boolean getIsAirlineWildCard() {
        return this.isAirlineWildCard;
    }

    public void setIsAirlineWildCard(boolean isAirlineWildCard) {
        this.isAirlineWildCard = isAirlineWildCard;
    }

    /**
     * CouponSaleType
     */
    public MultiCurrencyCouponStrategyType getStrategy() {
        return this.strategy;
    }

    public void setStrategy(MultiCurrencyCouponStrategyType strategy) {
        this.strategy = strategy;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final MultiCurrencyCouponInfo other = (MultiCurrencyCouponInfo)obj;
        return
            Objects.equal(this.couponCode, other.couponCode) && 
            Objects.equal(this.couponType, other.couponType) && 
            Objects.equal(this.startDate, other.startDate) && 
            Objects.equal(this.endDate, other.endDate) && 
            Objects.equal(this.currency, other.currency) && 
            Objects.equal(this.airlines, other.airlines) && 
            Objects.equal(this.couponSaleTypes, other.couponSaleTypes) && 
            Objects.equal(this.isAirlineWildCard, other.isAirlineWildCard) && 
            Objects.equal(this.strategy, other.strategy);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.couponCode);
        result = 31 * result + Objects.hashCode(this.couponType);
        result = 31 * result + Objects.hashCode(this.startDate);
        result = 31 * result + Objects.hashCode(this.endDate);
        result = 31 * result + Objects.hashCode(this.currency);
        result = 31 * result + Objects.hashCode(this.airlines);
        result = 31 * result + Objects.hashCode(this.couponSaleTypes);
        result = 31 * result + Objects.hashCode(this.isAirlineWildCard);
        result = 31 * result + Objects.hashCode(this.strategy);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("couponCode", couponCode)
            .add("couponType", couponType)
            .add("startDate", startDate)
            .add("endDate", endDate)
            .add("currency", currency)
            .add("airlines", airlines)
            .add("couponSaleTypes", couponSaleTypes)
            .add("isAirlineWildCard", isAirlineWildCard)
            .add("strategy", strategy)
            .toString();
    }
}