/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.paymentnotify.gaquerybillinfo.v1;

import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Bill单详情响应
 */
@DtoDoc("Bill单详情响应")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GaQueryBillInfoResponse", namespace = "http://soa.ctrip.com/Global/API/PaymentNotify/GaQueryBillInfo/v1")
@XmlType(name = "GaQueryBillInfoResponse", propOrder = {
    "responseStatus",
    "externalNo",
    "exchangeRate",
    "currency",
    "isRealCardRisk",
    "paidAmount",
    "realAmount",
    "transactionID",
    "status",
    "relatedBillNos",
    "paymentDetailList"
})
@SuppressWarnings("all")
public class GaQueryBillInfoResponse implements HasResponseStatus {

    private static final long serialVersionUID = 1L;

    public GaQueryBillInfoResponse(
        ResponseStatusType responseStatus, 
        String externalNo, 
        BigDecimal exchangeRate, 
        String currency, 
        boolean isRealCardRisk, 
        BigDecimal paidAmount, 
        BigDecimal realAmount, 
        String transactionID, 
        String status, 
        String relatedBillNos, 
        List<PaymentDetail> paymentDetailList) {
        this.responseStatus = responseStatus;
        this.externalNo = externalNo;
        this.exchangeRate = exchangeRate;
        this.currency = currency;
        this.isRealCardRisk = isRealCardRisk;
        this.paidAmount = paidAmount;
        this.realAmount = realAmount;
        this.transactionID = transactionID;
        this.status = status;
        this.relatedBillNos = relatedBillNos;
        this.paymentDetailList = paymentDetailList;
    }

    public GaQueryBillInfoResponse() {
    }

    @FieldDoc("SOA2.0返回头部信息")
    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @FieldDoc("币种")
    @JsonProperty("ExternalNo")
    @XmlElement(name = "ExternalNo")
    private String externalNo;

    @FieldDoc("汇率")
    @JsonProperty("ExchangeRate")
    @XmlElement(name = "ExchangeRate")
    private BigDecimal exchangeRate;

    @FieldDoc("币种")
    @JsonProperty("Currency")
    @XmlElement(name = "Currency")
    private String currency;

    @FieldDoc("IsRealCardRisk")
    @JsonProperty("IsRealCardRisk")
    @XmlElement(name = "IsRealCardRisk")
    private boolean isRealCardRisk;

    @FieldDoc("已收金额")
    @JsonProperty("PaidAmount")
    @XmlElement(name = "PaidAmount")
    private BigDecimal paidAmount;

    @FieldDoc("应收金额")
    @JsonProperty("RealAmount")
    @XmlElement(name = "RealAmount")
    private BigDecimal realAmount;

    @FieldDoc("流水号")
    @JsonProperty("TransactionID")
    @XmlElement(name = "TransactionID")
    private String transactionID;

    @FieldDoc("状态(客户端)")
    @JsonProperty("Status")
    @XmlElement(name = "Status")
    private String status;

    @FieldDoc("ExternalNo关联的Bill号")
    @JsonProperty("RelatedBillNos")
    @XmlElement(name = "RelatedBillNos")
    private String relatedBillNos;

    @FieldDoc("Bill单 列表")
    @JsonProperty("PaymentDetailList")
    @XmlElement(name = "PaymentDetailList")
    private List<PaymentDetail> paymentDetailList;

    /**
     * SOA2.0返回头部信息
     */
    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * 币种
     */
    public String getExternalNo() {
        return this.externalNo;
    }

    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo;
    }

    /**
     * 汇率
     */
    public BigDecimal getExchangeRate() {
        return this.exchangeRate;
    }

    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * 币种
     */
    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * IsRealCardRisk
     */
    public boolean getIsRealCardRisk() {
        return this.isRealCardRisk;
    }

    public void setIsRealCardRisk(boolean isRealCardRisk) {
        this.isRealCardRisk = isRealCardRisk;
    }

    /**
     * 已收金额
     */
    public BigDecimal getPaidAmount() {
        return this.paidAmount;
    }

    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    /**
     * 应收金额
     */
    public BigDecimal getRealAmount() {
        return this.realAmount;
    }

    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    /**
     * 流水号
     */
    public String getTransactionID() {
        return this.transactionID;
    }

    public void setTransactionID(String transactionID) {
        this.transactionID = transactionID;
    }

    /**
     * 状态(客户端)
     */
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * ExternalNo关联的Bill号
     */
    public String getRelatedBillNos() {
        return this.relatedBillNos;
    }

    public void setRelatedBillNos(String relatedBillNos) {
        this.relatedBillNos = relatedBillNos;
    }

    /**
     * Bill单 列表
     */
    public List<PaymentDetail> getPaymentDetailList() {
        return this.paymentDetailList;
    }

    public void setPaymentDetailList(List<PaymentDetail> paymentDetailList) {
        this.paymentDetailList = paymentDetailList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GaQueryBillInfoResponse other = (GaQueryBillInfoResponse)obj;
        return
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.externalNo, other.externalNo) && 
            Objects.equal(this.exchangeRate, other.exchangeRate) && 
            Objects.equal(this.currency, other.currency) && 
            Objects.equal(this.isRealCardRisk, other.isRealCardRisk) && 
            Objects.equal(this.paidAmount, other.paidAmount) && 
            Objects.equal(this.realAmount, other.realAmount) && 
            Objects.equal(this.transactionID, other.transactionID) && 
            Objects.equal(this.status, other.status) && 
            Objects.equal(this.relatedBillNos, other.relatedBillNos) && 
            Objects.equal(this.paymentDetailList, other.paymentDetailList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.externalNo);
        result = 31 * result + Objects.hashCode(this.exchangeRate);
        result = 31 * result + Objects.hashCode(this.currency);
        result = 31 * result + Objects.hashCode(this.isRealCardRisk);
        result = 31 * result + Objects.hashCode(this.paidAmount);
        result = 31 * result + Objects.hashCode(this.realAmount);
        result = 31 * result + Objects.hashCode(this.transactionID);
        result = 31 * result + Objects.hashCode(this.status);
        result = 31 * result + Objects.hashCode(this.relatedBillNos);
        result = 31 * result + Objects.hashCode(this.paymentDetailList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseStatus", responseStatus)
            .add("externalNo", externalNo)
            .add("exchangeRate", exchangeRate)
            .add("currency", currency)
            .add("isRealCardRisk", isRealCardRisk)
            .add("paidAmount", paidAmount)
            .add("realAmount", realAmount)
            .add("transactionID", transactionID)
            .add("status", status)
            .add("relatedBillNos", relatedBillNos)
            .add("paymentDetailList", paymentDetailList)
            .toString();
    }
}