// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.generatetoken.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * Token类型
 */
@XmlType(name = "TokenType")
@XmlEnum
@SuppressWarnings("all")
public enum TokenType {

    @XmlEnumValue("Distribution")
    Distribution(0, "Distribution"),

    @XmlEnumValue("Other")
    Other(1, "Other");

    private final int intValue;
    private final String value;

    TokenType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static TokenType fromValue(String v) {
        for (TokenType e: TokenType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static TokenType findByValue(int value) {
        switch (value) {
            case 0:
                return Distribution;
            case 1:
                return Other;
            default:
                return null;
        }
    }
}