/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.searhflightporduct.v1;

import com.ctrip.soa.global.api.flightcommon.v1.ColunmInfo;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 已选航班
 */
@DtoDoc("已选航班")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedFlightInfo", propOrder = {
    "segNo",
    "colunmInfoList"
})
@SuppressWarnings("all")
public class SelectedFlightInfo  {

    private static final long serialVersionUID = 1L;

    public SelectedFlightInfo(
        int segNo, 
        List<ColunmInfo> colunmInfoList) {
        this.segNo = segNo;
        this.colunmInfoList = colunmInfoList;
    }

    public SelectedFlightInfo() {
    }

    @FieldDoc("航段序号")
    @JsonProperty("SegNo")
    @XmlElement(name = "SegNo")
    private int segNo;

    @FieldDoc("航段信息")
    @JsonProperty("ColunmInfoList")
    @XmlElement(name = "ColunmInfoList")
    private List<ColunmInfo> colunmInfoList;

    /**
     * 航段序号
     */
    public int getSegNo() {
        return this.segNo;
    }

    public void setSegNo(int segNo) {
        this.segNo = segNo;
    }

    /**
     * 航段信息
     */
    public List<ColunmInfo> getColunmInfoList() {
        return this.colunmInfoList;
    }

    public void setColunmInfoList(List<ColunmInfo> colunmInfoList) {
        this.colunmInfoList = colunmInfoList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final SelectedFlightInfo other = (SelectedFlightInfo)obj;
        return
            Objects.equal(this.segNo, other.segNo) && 
            Objects.equal(this.colunmInfoList, other.colunmInfoList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.segNo);
        result = 31 * result + Objects.hashCode(this.colunmInfoList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("segNo", segNo)
            .add("colunmInfoList", colunmInfoList)
            .toString();
    }
}