// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.searhflightporduct.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 中转类型
 */
@XmlType(name = "TransitType")
@XmlEnum
@SuppressWarnings("all")
public enum TransitType {

    /**
     * 直飞
     */
    @XmlEnumValue("Direct")
    Direct(0, "Direct"),

    /**
     * 一次中转
     */
    @XmlEnumValue("OneStop")
    OneStop(1, "OneStop"),

    /**
     * 多次中转
     */
    @XmlEnumValue("Multi")
    Multi(2, "Multi");

    private final int intValue;
    private final String value;

    TransitType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static TransitType fromValue(String v) {
        for (TransitType e: TransitType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static TransitType findByValue(int value) {
        switch (value) {
            case 0:
                return Direct;
            case 1:
                return OneStop;
            case 2:
                return Multi;
            default:
                return null;
        }
    }
}