/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gareschedulequery.v1;

import com.ctrip.soa.global.api.comm.responsehead.v1.ResponseHead;
import com.ctrip.soa.global.api.searhflightporduct.v1.FltProductInfo;
import com.ctrip.soa.global.api.searhflightporduct.v1.SelectedFlightInfo;
import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 机票改签航班查询返回
 */
@DtoDoc("机票改签航班查询返回")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GaRescheduleQueryResponse", namespace = "http://soa.ctrip.com/Global/API/GaRescheduleQuery/v1")
@XmlType(name = "GaRescheduleQueryResponse", propOrder = {
    "responseHead",
    "responseStatus",
    "no",
    "searchCriteriaToken",
    "flightOrderClass",
    "fltProductInfoList",
    "selectedFltProductInfoList"
})
@SuppressWarnings("all")
public class GaRescheduleQueryResponse implements HasResponseStatus {

    private static final long serialVersionUID = 1L;

    public GaRescheduleQueryResponse(
        ResponseHead responseHead, 
        ResponseStatusType responseStatus, 
        int no, 
        String searchCriteriaToken, 
        String flightOrderClass, 
        List<FltProductInfo> fltProductInfoList, 
        List<SelectedFlightInfo> selectedFltProductInfoList) {
        this.responseHead = responseHead;
        this.responseStatus = responseStatus;
        this.no = no;
        this.searchCriteriaToken = searchCriteriaToken;
        this.flightOrderClass = flightOrderClass;
        this.fltProductInfoList = fltProductInfoList;
        this.selectedFltProductInfoList = selectedFltProductInfoList;
    }

    public GaRescheduleQueryResponse() {
    }

    @JsonProperty("ResponseHead")
    @XmlElement(name = "ResponseHead")
    private ResponseHead responseHead;

    @FieldDoc("SOA2.0返回头部信息")
    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @FieldDoc("返回序号，从1开始，去程1，返程2，类推")
    @JsonProperty("No")
    @XmlElement(name = "No")
    private int no;

    @FieldDoc("缓存流水号")
    @JsonProperty("SearchCriteriaToken")
    @XmlElement(name = "SearchCriteriaToken")
    private String searchCriteriaToken;

    @FieldDoc("I国际，N国内")
    @JsonProperty("FlightOrderClass")
    @XmlElement(name = "FlightOrderClass")
    private String flightOrderClass;

    @FieldDoc("航线产品信息")
    @JsonProperty("FltProductInfoList")
    @XmlElement(name = "FltProductInfoList")
    private List<FltProductInfo> fltProductInfoList;

    @FieldDoc("已选航班信息列表，去程时为空")
    @JsonProperty("SelectedFltProductInfoList")
    @XmlElement(name = "SelectedFltProductInfo")
    @XmlElementWrapper(name = "SelectedFltProductInfoList")
    private List<SelectedFlightInfo> selectedFltProductInfoList;

    public ResponseHead getResponseHead() {
        return this.responseHead;
    }

    public void setResponseHead(ResponseHead responseHead) {
        this.responseHead = responseHead;
    }

    /**
     * SOA2.0返回头部信息
     */
    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * 返回序号，从1开始，去程1，返程2，类推
     */
    public int getNo() {
        return this.no;
    }

    public void setNo(int no) {
        this.no = no;
    }

    /**
     * 缓存流水号
     */
    public String getSearchCriteriaToken() {
        return this.searchCriteriaToken;
    }

    public void setSearchCriteriaToken(String searchCriteriaToken) {
        this.searchCriteriaToken = searchCriteriaToken;
    }

    /**
     * I国际，N国内
     */
    public String getFlightOrderClass() {
        return this.flightOrderClass;
    }

    public void setFlightOrderClass(String flightOrderClass) {
        this.flightOrderClass = flightOrderClass;
    }

    /**
     * 航线产品信息
     */
    public List<FltProductInfo> getFltProductInfoList() {
        return this.fltProductInfoList;
    }

    public void setFltProductInfoList(List<FltProductInfo> fltProductInfoList) {
        this.fltProductInfoList = fltProductInfoList;
    }

    /**
     * 已选航班信息列表，去程时为空
     */
    public List<SelectedFlightInfo> getSelectedFltProductInfoList() {
        return this.selectedFltProductInfoList;
    }

    public void setSelectedFltProductInfoList(List<SelectedFlightInfo> selectedFltProductInfoList) {
        this.selectedFltProductInfoList = selectedFltProductInfoList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GaRescheduleQueryResponse other = (GaRescheduleQueryResponse)obj;
        return
            Objects.equal(this.responseHead, other.responseHead) && 
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.no, other.no) && 
            Objects.equal(this.searchCriteriaToken, other.searchCriteriaToken) && 
            Objects.equal(this.flightOrderClass, other.flightOrderClass) && 
            Objects.equal(this.fltProductInfoList, other.fltProductInfoList) && 
            Objects.equal(this.selectedFltProductInfoList, other.selectedFltProductInfoList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseHead);
        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.no);
        result = 31 * result + Objects.hashCode(this.searchCriteriaToken);
        result = 31 * result + Objects.hashCode(this.flightOrderClass);
        result = 31 * result + Objects.hashCode(this.fltProductInfoList);
        result = 31 * result + Objects.hashCode(this.selectedFltProductInfoList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseHead", responseHead)
            .add("responseStatus", responseStatus)
            .add("no", no)
            .add("searchCriteriaToken", searchCriteriaToken)
            .add("flightOrderClass", flightOrderClass)
            .add("fltProductInfoList", fltProductInfoList)
            .add("selectedFltProductInfoList", selectedFltProductInfoList)
            .toString();
    }
}