/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gacancelflightorder.v1;

import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 国际机票提交订单返回值
 */
@DtoDoc("国际机票提交订单返回值")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GaCancelFlightOrderResponse", namespace = "http://soa.ctrip.com/Global/API/GaCancelFlightOrder/v1")
@XmlType(name = "GaCancelFlightOrderResponse", propOrder = {
    "responseStatus",
    "errorMsg",
    "result",
    "messageCode"
})
@SuppressWarnings("all")
public class GaCancelFlightOrderResponse implements HasResponseStatus {

    private static final long serialVersionUID = 1L;

    public GaCancelFlightOrderResponse(
        ResponseStatusType responseStatus, 
        String errorMsg, 
        boolean result, 
        String messageCode) {
        this.responseStatus = responseStatus;
        this.errorMsg = errorMsg;
        this.result = result;
        this.messageCode = messageCode;
    }

    public GaCancelFlightOrderResponse() {
    }

    @FieldDoc("SOA2.0返回头部信息")
    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @FieldDoc("错误消息,正确为空")
    @JsonProperty("ErrorMsg")
    @XmlElement(name = "ErrorMsg")
    private String errorMsg;

    @FieldDoc("执行结果")
    @JsonProperty("Result")
    @XmlElement(name = "Result")
    private boolean result;

    @FieldDoc("返回消息MessageCode" +
          "0--成功" +
          "101--出票中，取消结果等通知" +
          "102--已出票" +
          "103--取消失败")
    @JsonProperty("MessageCode")
    @XmlElement(name = "MessageCode")
    private String messageCode;

    /**
     * SOA2.0返回头部信息
     */
    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * 错误消息,正确为空
     */
    public String getErrorMsg() {
        return this.errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * 执行结果
     */
    public boolean getResult() {
        return this.result;
    }

    public void setResult(boolean result) {
        this.result = result;
    }

    /**
     * 返回消息MessageCode
     *           0--成功
     *           101--出票中，取消结果等通知
     *           102--已出票
     *           103--取消失败
     */
    public String getMessageCode() {
        return this.messageCode;
    }

    public void setMessageCode(String messageCode) {
        this.messageCode = messageCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GaCancelFlightOrderResponse other = (GaCancelFlightOrderResponse)obj;
        return
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.errorMsg, other.errorMsg) && 
            Objects.equal(this.result, other.result) && 
            Objects.equal(this.messageCode, other.messageCode);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.errorMsg);
        result = 31 * result + Objects.hashCode(this.result);
        result = 31 * result + Objects.hashCode(this.messageCode);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseStatus", responseStatus)
            .add("errorMsg", errorMsg)
            .add("result", result)
            .add("messageCode", messageCode)
            .toString();
    }
}