/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gacreateflightintlorder.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 酒店优惠券详细信息
 */
@DtoDoc("酒店优惠券详细信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelCouponProductType", propOrder = {
    "hotelCouponID",
    "hotelCouponNum"
})
@SuppressWarnings("all")
public class HotelCouponProductType  {

    private static final long serialVersionUID = 1L;

    public HotelCouponProductType(
        long hotelCouponID, 
        int hotelCouponNum) {
        this.hotelCouponID = hotelCouponID;
        this.hotelCouponNum = hotelCouponNum;
    }

    public HotelCouponProductType() {
    }

    @FieldDoc("优惠券ID")
    @JsonProperty("HotelCouponID")
    @XmlElement(name = "HotelCouponID")
    private long hotelCouponID;

    @FieldDoc("酒店优惠券")
    @JsonProperty("HotelCouponNum")
    @XmlElement(name = "HotelCouponNum")
    private int hotelCouponNum;

    /**
     * 优惠券ID
     */
    public long getHotelCouponID() {
        return this.hotelCouponID;
    }

    public void setHotelCouponID(long hotelCouponID) {
        this.hotelCouponID = hotelCouponID;
    }

    /**
     * 酒店优惠券
     */
    public int getHotelCouponNum() {
        return this.hotelCouponNum;
    }

    public void setHotelCouponNum(int hotelCouponNum) {
        this.hotelCouponNum = hotelCouponNum;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final HotelCouponProductType other = (HotelCouponProductType)obj;
        return
            Objects.equal(this.hotelCouponID, other.hotelCouponID) && 
            Objects.equal(this.hotelCouponNum, other.hotelCouponNum);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.hotelCouponID);
        result = 31 * result + Objects.hashCode(this.hotelCouponNum);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("hotelCouponID", hotelCouponID)
            .add("hotelCouponNum", hotelCouponNum)
            .toString();
    }
}