/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gacreateflightintlorder.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 乘机人所选行李额列表
 */
@DtoDoc("乘机人所选行李额列表")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueAddServiceBaggageInfoType", propOrder = {
    "hasPurchasedBaggageService",
    "valueAddServiceBaggageList"
})
@SuppressWarnings("all")
public class ValueAddServiceBaggageInfoType  {

    private static final long serialVersionUID = 1L;

    public ValueAddServiceBaggageInfoType(
        boolean hasPurchasedBaggageService, 
        List<PassengerValueAddInfoType> valueAddServiceBaggageList) {
        this.hasPurchasedBaggageService = hasPurchasedBaggageService;
        this.valueAddServiceBaggageList = valueAddServiceBaggageList;
    }

    public ValueAddServiceBaggageInfoType() {
    }

    @FieldDoc("是否购买了行李额服务")
    @JsonProperty("HasPurchasedBaggageService")
    @XmlElement(name = "HasPurchasedBaggageService")
    private boolean hasPurchasedBaggageService;

    @FieldDoc("乘机人及所选行李额列表")
    @JsonProperty("ValueAddServiceBaggageList")
    @XmlElement(name = "ValueAddServiceBaggageList")
    private List<PassengerValueAddInfoType> valueAddServiceBaggageList;

    /**
     * 是否购买了行李额服务
     */
    public boolean getHasPurchasedBaggageService() {
        return this.hasPurchasedBaggageService;
    }

    public void setHasPurchasedBaggageService(boolean hasPurchasedBaggageService) {
        this.hasPurchasedBaggageService = hasPurchasedBaggageService;
    }

    /**
     * 乘机人及所选行李额列表
     */
    public List<PassengerValueAddInfoType> getValueAddServiceBaggageList() {
        return this.valueAddServiceBaggageList;
    }

    public void setValueAddServiceBaggageList(List<PassengerValueAddInfoType> valueAddServiceBaggageList) {
        this.valueAddServiceBaggageList = valueAddServiceBaggageList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ValueAddServiceBaggageInfoType other = (ValueAddServiceBaggageInfoType)obj;
        return
            Objects.equal(this.hasPurchasedBaggageService, other.hasPurchasedBaggageService) && 
            Objects.equal(this.valueAddServiceBaggageList, other.valueAddServiceBaggageList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.hasPurchasedBaggageService);
        result = 31 * result + Objects.hashCode(this.valueAddServiceBaggageList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("hasPurchasedBaggageService", hasPurchasedBaggageService)
            .add("valueAddServiceBaggageList", valueAddServiceBaggageList)
            .toString();
    }
}