/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gaflightpaymentnotifyforonlinedomestic.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 订单完成通知支付结果
 */
@DtoDoc("订单完成通知支付结果")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GaFlightPaymentNotifyForOnlineIntlRequest", namespace = "http://soa.ctrip.com/Global/API/GaFlightPaymentNotifyForOnlineIntl/v1")
@XmlType(name = "FlightsOnlinePaymentNotifyRequest", propOrder = {
    "version",
    "businessType",
    "channelSource",
    "baseInfo",
    "language",
    "payInfo"
})
@SuppressWarnings("all")
public class FlightsOnlinePaymentNotifyRequest  {

    private static final long serialVersionUID = 1L;

    public FlightsOnlinePaymentNotifyRequest(
        int version, 
        int businessType, 
        int channelSource, 
        NotifyBaseInformation baseInfo, 
        String language, 
        List<NotifyPayInformation> payInfo) {
        this.version = version;
        this.businessType = businessType;
        this.channelSource = channelSource;
        this.baseInfo = baseInfo;
        this.language = language;
        this.payInfo = payInfo;
    }

    public FlightsOnlinePaymentNotifyRequest() {
    }

    @FieldDoc("当前版本为1")
    @JsonProperty("Version")
    @XmlElement(name = "Version")
    private int version;

    @FieldDoc("业务类型（参考4.2支付平台商户代码）")
    @JsonProperty("BusinessType")
    @XmlElement(name = "BusinessType")
    private int businessType;

    @FieldDoc("渠道")
    @JsonProperty("ChannelSource")
    @XmlElement(name = "ChannelSource")
    private int channelSource;

    @FieldDoc("基本通知信息")
    @JsonProperty("BaseInfo")
    @XmlElement(name = "BaseInfo")
    private NotifyBaseInformation baseInfo;

    @FieldDoc("语言String(8)")
    @JsonProperty("Language")
    @XmlElement(name = "Language")
    private String language;

    @FieldDoc("支付信息")
    @JsonProperty("PayInfo")
    @XmlElement(name = "PayInfo")
    private List<NotifyPayInformation> payInfo;

    /**
     * 当前版本为1
     */
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    /**
     * 业务类型（参考4.2支付平台商户代码）
     */
    public int getBusinessType() {
        return this.businessType;
    }

    public void setBusinessType(int businessType) {
        this.businessType = businessType;
    }

    /**
     * 渠道
     */
    public int getChannelSource() {
        return this.channelSource;
    }

    public void setChannelSource(int channelSource) {
        this.channelSource = channelSource;
    }

    /**
     * 基本通知信息
     */
    public NotifyBaseInformation getBaseInfo() {
        return this.baseInfo;
    }

    public void setBaseInfo(NotifyBaseInformation baseInfo) {
        this.baseInfo = baseInfo;
    }

    /**
     * 语言String(8)
     */
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * 支付信息
     */
    public List<NotifyPayInformation> getPayInfo() {
        return this.payInfo;
    }

    public void setPayInfo(List<NotifyPayInformation> payInfo) {
        this.payInfo = payInfo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final FlightsOnlinePaymentNotifyRequest other = (FlightsOnlinePaymentNotifyRequest)obj;
        return
            Objects.equal(this.version, other.version) && 
            Objects.equal(this.businessType, other.businessType) && 
            Objects.equal(this.channelSource, other.channelSource) && 
            Objects.equal(this.baseInfo, other.baseInfo) && 
            Objects.equal(this.language, other.language) && 
            Objects.equal(this.payInfo, other.payInfo);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.version);
        result = 31 * result + Objects.hashCode(this.businessType);
        result = 31 * result + Objects.hashCode(this.channelSource);
        result = 31 * result + Objects.hashCode(this.baseInfo);
        result = 31 * result + Objects.hashCode(this.language);
        result = 31 * result + Objects.hashCode(this.payInfo);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("version", version)
            .add("businessType", businessType)
            .add("channelSource", channelSource)
            .add("baseInfo", baseInfo)
            .add("language", language)
            .add("payInfo", payInfo)
            .toString();
    }
}