/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.orderdetailsearch.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 退票明细
 */
@DtoDoc("退票明细")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundDetailInfo", propOrder = {
    "passengerName",
    "refundFee",
    "cnyRefundFee",
    "isCanCalculate",
    "flight",
    "sequence",
    "subsidy",
    "cnySubsidy"
})
@SuppressWarnings("all")
public class RefundDetailInfo  {

    private static final long serialVersionUID = 1L;

    public RefundDetailInfo(
        String passengerName, 
        BigDecimal refundFee, 
        BigDecimal cnyRefundFee, 
        boolean isCanCalculate, 
        String flight, 
        int sequence, 
        BigDecimal subsidy, 
        BigDecimal cnySubsidy) {
        this.passengerName = passengerName;
        this.refundFee = refundFee;
        this.cnyRefundFee = cnyRefundFee;
        this.isCanCalculate = isCanCalculate;
        this.flight = flight;
        this.sequence = sequence;
        this.subsidy = subsidy;
        this.cnySubsidy = cnySubsidy;
    }

    public RefundDetailInfo() {
    }

    @FieldDoc("状态")
    @JsonProperty("PassengerName")
    @XmlElement(name = "PassengerName")
    private String passengerName;

    @FieldDoc("退票费(支付币种)")
    @JsonProperty("RefundFee")
    @XmlElement(name = "RefundFee")
    private BigDecimal refundFee;

    @FieldDoc("退票费(人民币)")
    @JsonProperty("CNYRefundFee")
    @XmlElement(name = "CNYRefundFee")
    private BigDecimal cnyRefundFee;

    @FieldDoc("退票费是否可计算")
    @JsonProperty("IsCanCalculate")
    @XmlElement(name = "IsCanCalculate")
    private boolean isCanCalculate;

    @FieldDoc("航班号")
    @JsonProperty("Flight")
    @XmlElement(name = "Flight")
    private String flight;

    @FieldDoc("航段号")
    @JsonProperty("Sequence")
    @XmlElement(name = "Sequence")
    private int sequence;

    @FieldDoc("飞享金 (支付币种)")
    @JsonProperty("Subsidy")
    @XmlElement(name = "Subsidy")
    private BigDecimal subsidy;

    @FieldDoc("飞享金(人民币)")
    @JsonProperty("CNYSubsidy")
    @XmlElement(name = "CNYSubsidy")
    private BigDecimal cnySubsidy;

    /**
     * 状态
     */
    public String getPassengerName() {
        return this.passengerName;
    }

    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    /**
     * 退票费(支付币种)
     */
    public BigDecimal getRefundFee() {
        return this.refundFee;
    }

    public void setRefundFee(BigDecimal refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * 退票费(人民币)
     */
    public BigDecimal getCnyRefundFee() {
        return this.cnyRefundFee;
    }

    public void setCnyRefundFee(BigDecimal cnyRefundFee) {
        this.cnyRefundFee = cnyRefundFee;
    }

    /**
     * 退票费是否可计算
     */
    public boolean getIsCanCalculate() {
        return this.isCanCalculate;
    }

    public void setIsCanCalculate(boolean isCanCalculate) {
        this.isCanCalculate = isCanCalculate;
    }

    /**
     * 航班号
     */
    public String getFlight() {
        return this.flight;
    }

    public void setFlight(String flight) {
        this.flight = flight;
    }

    /**
     * 航段号
     */
    public int getSequence() {
        return this.sequence;
    }

    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    /**
     * 飞享金 (支付币种)
     */
    public BigDecimal getSubsidy() {
        return this.subsidy;
    }

    public void setSubsidy(BigDecimal subsidy) {
        this.subsidy = subsidy;
    }

    /**
     * 飞享金(人民币)
     */
    public BigDecimal getCnySubsidy() {
        return this.cnySubsidy;
    }

    public void setCnySubsidy(BigDecimal cnySubsidy) {
        this.cnySubsidy = cnySubsidy;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final RefundDetailInfo other = (RefundDetailInfo)obj;
        return
            Objects.equal(this.passengerName, other.passengerName) && 
            Objects.equal(this.refundFee, other.refundFee) && 
            Objects.equal(this.cnyRefundFee, other.cnyRefundFee) && 
            Objects.equal(this.isCanCalculate, other.isCanCalculate) && 
            Objects.equal(this.flight, other.flight) && 
            Objects.equal(this.sequence, other.sequence) && 
            Objects.equal(this.subsidy, other.subsidy) && 
            Objects.equal(this.cnySubsidy, other.cnySubsidy);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.passengerName);
        result = 31 * result + Objects.hashCode(this.refundFee);
        result = 31 * result + Objects.hashCode(this.cnyRefundFee);
        result = 31 * result + Objects.hashCode(this.isCanCalculate);
        result = 31 * result + Objects.hashCode(this.flight);
        result = 31 * result + Objects.hashCode(this.sequence);
        result = 31 * result + Objects.hashCode(this.subsidy);
        result = 31 * result + Objects.hashCode(this.cnySubsidy);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("passengerName", passengerName)
            .add("refundFee", refundFee)
            .add("cnyRefundFee", cnyRefundFee)
            .add("isCanCalculate", isCanCalculate)
            .add("flight", flight)
            .add("sequence", sequence)
            .add("subsidy", subsidy)
            .add("cnySubsidy", cnySubsidy)
            .toString();
    }
}