/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.soa.resource.v1;

import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "WarningListRequest", namespace = "http://soa.ctrip.com/global/soa/resource/v1")
@XmlType(name = "WarningListRequest", propOrder = {
    "warningType",
    "cityId",
    "hotelIDs",
    "hotelStar",
    "pageSize",
    "pageNo",
    "way",
    "startDateTime",
    "endDateTime",
    "resourceType"
})
@SuppressWarnings("all")
public class WarningListRequest  {

    private static final long serialVersionUID = 1L;

    public WarningListRequest(
        String warningType, 
        int cityId, 
        String hotelIDs, 
        int hotelStar, 
        int pageSize, 
        int pageNo, 
        String way, 
        Calendar startDateTime, 
        Calendar endDateTime, 
        String resourceType) {
        this.warningType = warningType;
        this.cityId = cityId;
        this.hotelIDs = hotelIDs;
        this.hotelStar = hotelStar;
        this.pageSize = pageSize;
        this.pageNo = pageNo;
        this.way = way;
        this.startDateTime = startDateTime;
        this.endDateTime = endDateTime;
        this.resourceType = resourceType;
    }

    public WarningListRequest() {
    }

    @FieldDoc("语言")
    @JsonProperty("WarningType")
    @XmlElement(name = "WarningType")
    private String warningType;

    @FieldDoc("城市ID")
    @JsonProperty("CityId")
    @XmlElement(name = "CityId")
    private int cityId;

    @FieldDoc("酒店ID列表，以逗号分隔，限制每次最多20个")
    @JsonProperty("HotelIDs")
    @XmlElement(name = "HotelIDs")
    private String hotelIDs;

    @FieldDoc("酒店星级")
    @JsonProperty("HotelStar")
    @XmlElement(name = "HotelStar")
    private int hotelStar;

    @FieldDoc("每页条数")
    @JsonProperty("PageSize")
    @XmlElement(name = "PageSize")
    private int pageSize;

    @FieldDoc("页码")
    @JsonProperty("PageNo")
    @XmlElement(name = "PageNo")
    private int pageNo;

    @FieldDoc("过滤方式（语言，城市ID，酒店ID，酒店星级）")
    @JsonProperty("Way")
    @XmlElement(name = "Way")
    private String way;

    @FieldDoc("开始时间")
    @JsonProperty("StartDateTime")
    @XmlElement(name = "StartDateTime")
    private Calendar startDateTime;

    @FieldDoc("结束时间")
    @JsonProperty("EndDateTime")
    @XmlElement(name = "EndDateTime")
    private Calendar endDateTime;

    @FieldDoc("资源类型")
    @JsonProperty("ResourceType")
    @XmlElement(name = "ResourceType")
    private String resourceType;

    /**
     * 语言
     */
    public String getWarningType() {
        return this.warningType;
    }

    public void setWarningType(String warningType) {
        this.warningType = warningType;
    }

    /**
     * 城市ID
     */
    public int getCityId() {
        return this.cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    /**
     * 酒店ID列表，以逗号分隔，限制每次最多20个
     */
    public String getHotelIDs() {
        return this.hotelIDs;
    }

    public void setHotelIDs(String hotelIDs) {
        this.hotelIDs = hotelIDs;
    }

    /**
     * 酒店星级
     */
    public int getHotelStar() {
        return this.hotelStar;
    }

    public void setHotelStar(int hotelStar) {
        this.hotelStar = hotelStar;
    }

    /**
     * 每页条数
     */
    public int getPageSize() {
        return this.pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * 页码
     */
    public int getPageNo() {
        return this.pageNo;
    }

    public void setPageNo(int pageNo) {
        this.pageNo = pageNo;
    }

    /**
     * 过滤方式（语言，城市ID，酒店ID，酒店星级）
     */
    public String getWay() {
        return this.way;
    }

    public void setWay(String way) {
        this.way = way;
    }

    /**
     * 开始时间
     */
    public Calendar getStartDateTime() {
        return this.startDateTime;
    }

    public void setStartDateTime(Calendar startDateTime) {
        this.startDateTime = startDateTime;
    }

    /**
     * 结束时间
     */
    public Calendar getEndDateTime() {
        return this.endDateTime;
    }

    public void setEndDateTime(Calendar endDateTime) {
        this.endDateTime = endDateTime;
    }

    /**
     * 资源类型
     */
    public String getResourceType() {
        return this.resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final WarningListRequest other = (WarningListRequest)obj;
        return
            Objects.equal(this.warningType, other.warningType) && 
            Objects.equal(this.cityId, other.cityId) && 
            Objects.equal(this.hotelIDs, other.hotelIDs) && 
            Objects.equal(this.hotelStar, other.hotelStar) && 
            Objects.equal(this.pageSize, other.pageSize) && 
            Objects.equal(this.pageNo, other.pageNo) && 
            Objects.equal(this.way, other.way) && 
            Objects.equal(this.startDateTime, other.startDateTime) && 
            Objects.equal(this.endDateTime, other.endDateTime) && 
            Objects.equal(this.resourceType, other.resourceType);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.warningType);
        result = 31 * result + Objects.hashCode(this.cityId);
        result = 31 * result + Objects.hashCode(this.hotelIDs);
        result = 31 * result + Objects.hashCode(this.hotelStar);
        result = 31 * result + Objects.hashCode(this.pageSize);
        result = 31 * result + Objects.hashCode(this.pageNo);
        result = 31 * result + Objects.hashCode(this.way);
        result = 31 * result + Objects.hashCode(this.startDateTime);
        result = 31 * result + Objects.hashCode(this.endDateTime);
        result = 31 * result + Objects.hashCode(this.resourceType);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("warningType", warningType)
            .add("cityId", cityId)
            .add("hotelIDs", hotelIDs)
            .add("hotelStar", hotelStar)
            .add("pageSize", pageSize)
            .add("pageNo", pageNo)
            .add("way", way)
            .add("startDateTime", startDateTime)
            .add("endDateTime", endDateTime)
            .add("resourceType", resourceType)
            .toString();
    }
}