/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gaintlxproductsearch.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 行李额重量信息
 */
@DtoDoc("行李额重量信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueAddedBaggageWeightInfo", propOrder = {
    "weightUnits",
    "weightRateToKilogram",
    "weight",
    "paidWeight",
    "freeWeight"
})
@SuppressWarnings("all")
public class ValueAddedBaggageWeightInfo  {

    private static final long serialVersionUID = 1L;

    public ValueAddedBaggageWeightInfo(
        String weightUnits, 
        BigDecimal weightRateToKilogram, 
        BigDecimal weight, 
        BigDecimal paidWeight, 
        BigDecimal freeWeight) {
        this.weightUnits = weightUnits;
        this.weightRateToKilogram = weightRateToKilogram;
        this.weight = weight;
        this.paidWeight = paidWeight;
        this.freeWeight = freeWeight;
    }

    public ValueAddedBaggageWeightInfo() {
    }

    @FieldDoc("重量单位")
    @JsonProperty("WeightUnits")
    @XmlElement(name = "WeightUnits")
    private String weightUnits;

    @FieldDoc("当前重量单位对千克的转换率")
    @JsonProperty("WeightRateToKilogram")
    @XmlElement(name = "WeightRateToKilogram")
    private BigDecimal weightRateToKilogram;

    @FieldDoc("行李额重量")
    @JsonProperty("Weight")
    @XmlElement(name = "Weight")
    private BigDecimal weight;

    @FieldDoc("支付行李重量(TF)")
    @JsonProperty("PaidWeight")
    @XmlElement(name = "PaidWeight")
    private BigDecimal paidWeight;

    @FieldDoc("免费行李重量(TF)")
    @JsonProperty("FreeWeight")
    @XmlElement(name = "FreeWeight")
    private BigDecimal freeWeight;

    /**
     * 重量单位
     */
    public String getWeightUnits() {
        return this.weightUnits;
    }

    public void setWeightUnits(String weightUnits) {
        this.weightUnits = weightUnits;
    }

    /**
     * 当前重量单位对千克的转换率
     */
    public BigDecimal getWeightRateToKilogram() {
        return this.weightRateToKilogram;
    }

    public void setWeightRateToKilogram(BigDecimal weightRateToKilogram) {
        this.weightRateToKilogram = weightRateToKilogram;
    }

    /**
     * 行李额重量
     */
    public BigDecimal getWeight() {
        return this.weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * 支付行李重量(TF)
     */
    public BigDecimal getPaidWeight() {
        return this.paidWeight;
    }

    public void setPaidWeight(BigDecimal paidWeight) {
        this.paidWeight = paidWeight;
    }

    /**
     * 免费行李重量(TF)
     */
    public BigDecimal getFreeWeight() {
        return this.freeWeight;
    }

    public void setFreeWeight(BigDecimal freeWeight) {
        this.freeWeight = freeWeight;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ValueAddedBaggageWeightInfo other = (ValueAddedBaggageWeightInfo)obj;
        return
            Objects.equal(this.weightUnits, other.weightUnits) && 
            Objects.equal(this.weightRateToKilogram, other.weightRateToKilogram) && 
            Objects.equal(this.weight, other.weight) && 
            Objects.equal(this.paidWeight, other.paidWeight) && 
            Objects.equal(this.freeWeight, other.freeWeight);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.weightUnits);
        result = 31 * result + Objects.hashCode(this.weightRateToKilogram);
        result = 31 * result + Objects.hashCode(this.weight);
        result = 31 * result + Objects.hashCode(this.paidWeight);
        result = 31 * result + Objects.hashCode(this.freeWeight);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("weightUnits", weightUnits)
            .add("weightRateToKilogram", weightRateToKilogram)
            .add("weight", weight)
            .add("paidWeight", paidWeight)
            .add("freeWeight", freeWeight)
            .toString();
    }
}