/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.getlowpriceincalender.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 低价日历实体
 */
@DtoDoc("低价日历实体")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LowPriceInCalenderDto", propOrder = {
    "dDateLong",
    "dDateDisplayValue",
    "originPrice",
    "currencyPrice",
    "currencyPriceDisplayValue"
})
@SuppressWarnings("all")
public class LowPriceInCalenderDto  {

    private static final long serialVersionUID = 1L;

    public LowPriceInCalenderDto(
        long dDateLong, 
        String dDateDisplayValue, 
        BigDecimal originPrice, 
        BigDecimal currencyPrice, 
        String currencyPriceDisplayValue) {
        this.dDateLong = dDateLong;
        this.dDateDisplayValue = dDateDisplayValue;
        this.originPrice = originPrice;
        this.currencyPrice = currencyPrice;
        this.currencyPriceDisplayValue = currencyPriceDisplayValue;
    }

    public LowPriceInCalenderDto() {
    }

    @FieldDoc("出发日期")
    @JsonProperty("DDateLong")
    @XmlElement(name = "DDateLong")
    private long dDateLong;

    @FieldDoc("出发日期，多语言格式")
    @JsonProperty("DDateDisplayValue")
    @XmlElement(name = "DDateDisplayValue")
    private String dDateDisplayValue;

    @FieldDoc("原始价格")
    @JsonProperty("OriginPrice")
    @XmlElement(name = "OriginPrice")
    private BigDecimal originPrice;

    @FieldDoc("对应币种价格")
    @JsonProperty("CurrencyPrice")
    @XmlElement(name = "CurrencyPrice")
    private BigDecimal currencyPrice;

    @FieldDoc("对应币种价格展示字符串，多语言格式")
    @JsonProperty("CurrencyPriceDisplayValue")
    @XmlElement(name = "CurrencyPriceDisplayValue")
    private String currencyPriceDisplayValue;

    /**
     * 出发日期
     */
    public long getDDateLong() {
        return this.dDateLong;
    }

    public void setDDateLong(long dDateLong) {
        this.dDateLong = dDateLong;
    }

    /**
     * 出发日期，多语言格式
     */
    public String getDDateDisplayValue() {
        return this.dDateDisplayValue;
    }

    public void setDDateDisplayValue(String dDateDisplayValue) {
        this.dDateDisplayValue = dDateDisplayValue;
    }

    /**
     * 原始价格
     */
    public BigDecimal getOriginPrice() {
        return this.originPrice;
    }

    public void setOriginPrice(BigDecimal originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * 对应币种价格
     */
    public BigDecimal getCurrencyPrice() {
        return this.currencyPrice;
    }

    public void setCurrencyPrice(BigDecimal currencyPrice) {
        this.currencyPrice = currencyPrice;
    }

    /**
     * 对应币种价格展示字符串，多语言格式
     */
    public String getCurrencyPriceDisplayValue() {
        return this.currencyPriceDisplayValue;
    }

    public void setCurrencyPriceDisplayValue(String currencyPriceDisplayValue) {
        this.currencyPriceDisplayValue = currencyPriceDisplayValue;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final LowPriceInCalenderDto other = (LowPriceInCalenderDto)obj;
        return
            Objects.equal(this.dDateLong, other.dDateLong) && 
            Objects.equal(this.dDateDisplayValue, other.dDateDisplayValue) && 
            Objects.equal(this.originPrice, other.originPrice) && 
            Objects.equal(this.currencyPrice, other.currencyPrice) && 
            Objects.equal(this.currencyPriceDisplayValue, other.currencyPriceDisplayValue);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.dDateLong);
        result = 31 * result + Objects.hashCode(this.dDateDisplayValue);
        result = 31 * result + Objects.hashCode(this.originPrice);
        result = 31 * result + Objects.hashCode(this.currencyPrice);
        result = 31 * result + Objects.hashCode(this.currencyPriceDisplayValue);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("dDateLong", dDateLong)
            .add("dDateDisplayValue", dDateDisplayValue)
            .add("originPrice", originPrice)
            .add("currencyPrice", currencyPrice)
            .add("currencyPriceDisplayValue", currencyPriceDisplayValue)
            .toString();
    }
}