/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.intlflightcoupon.v1;

import com.ctrip.soa.global.api.comm.responsehead.v1.ResponseHead;
import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "IntlCouponResponse", namespace = "http://soa.ctrip.com/Global/API/IntlFlightCoupon/v1")
@XmlType(name = "IntlCouponResponse", propOrder = {
    "responseStatus",
    "couponInfo",
    "responseHead"
})
@SuppressWarnings("all")
public class IntlCouponResponse implements HasResponseStatus {

    private static final long serialVersionUID = 1L;

    public IntlCouponResponse(
        ResponseStatusType responseStatus, 
        CouponType couponInfo, 
        ResponseHead responseHead) {
        this.responseStatus = responseStatus;
        this.couponInfo = couponInfo;
        this.responseHead = responseHead;
    }

    public IntlCouponResponse() {
    }

    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @FieldDoc("优惠券信息")
    @JsonProperty("CouponInfo")
    @XmlElement(name = "CouponInfo")
    private CouponType couponInfo;

    @JsonProperty("ResponseHead")
    @XmlElement(name = "ResponseHead")
    private ResponseHead responseHead;

    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * 优惠券信息
     */
    public CouponType getCouponInfo() {
        return this.couponInfo;
    }

    public void setCouponInfo(CouponType couponInfo) {
        this.couponInfo = couponInfo;
    }

    public ResponseHead getResponseHead() {
        return this.responseHead;
    }

    public void setResponseHead(ResponseHead responseHead) {
        this.responseHead = responseHead;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final IntlCouponResponse other = (IntlCouponResponse)obj;
        return
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.couponInfo, other.couponInfo) && 
            Objects.equal(this.responseHead, other.responseHead);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.couponInfo);
        result = 31 * result + Objects.hashCode(this.responseHead);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseStatus", responseStatus)
            .add("couponInfo", couponInfo)
            .add("responseHead", responseHead)
            .toString();
    }
}