/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gagetflightintlpaymentandfulfillment.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 快递地址实体
 */
@DtoDoc("快递地址实体")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryRegionModel", propOrder = {
    "regionName",
    "regionNameEN",
    "cantonID",
    "description"
})
@SuppressWarnings("all")
public class DeliveryRegionModel  {

    private static final long serialVersionUID = 1L;

    public DeliveryRegionModel(
        String regionName, 
        String regionNameEN, 
        int cantonID, 
        String description) {
        this.regionName = regionName;
        this.regionNameEN = regionNameEN;
        this.cantonID = cantonID;
        this.description = description;
    }

    public DeliveryRegionModel() {
    }

    @FieldDoc("地区中文名称")
    @JsonProperty("RegionName")
    @XmlElement(name = "RegionName")
    private String regionName;

    @FieldDoc("地区英文名称")
    @JsonProperty("RegionNameEN")
    @XmlElement(name = "RegionNameEN")
    private String regionNameEN;

    @FieldDoc("地区ID")
    @JsonProperty("CantonID")
    @XmlElement(name = "CantonID")
    private int cantonID;

    @FieldDoc("地区描述")
    @JsonProperty("Description")
    @XmlElement(name = "Description")
    private String description;

    /**
     * 地区中文名称
     */
    public String getRegionName() {
        return this.regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * 地区英文名称
     */
    public String getRegionNameEN() {
        return this.regionNameEN;
    }

    public void setRegionNameEN(String regionNameEN) {
        this.regionNameEN = regionNameEN;
    }

    /**
     * 地区ID
     */
    public int getCantonID() {
        return this.cantonID;
    }

    public void setCantonID(int cantonID) {
        this.cantonID = cantonID;
    }

    /**
     * 地区描述
     */
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final DeliveryRegionModel other = (DeliveryRegionModel)obj;
        return
            Objects.equal(this.regionName, other.regionName) && 
            Objects.equal(this.regionNameEN, other.regionNameEN) && 
            Objects.equal(this.cantonID, other.cantonID) && 
            Objects.equal(this.description, other.description);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.regionName);
        result = 31 * result + Objects.hashCode(this.regionNameEN);
        result = 31 * result + Objects.hashCode(this.cantonID);
        result = 31 * result + Objects.hashCode(this.description);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("regionName", regionName)
            .add("regionNameEN", regionNameEN)
            .add("cantonID", cantonID)
            .add("description", description)
            .toString();
    }
}