/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gagetflightintlpaymentandfulfillment.v1;

import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 国际机票获取配送及支付信息请
 */
@DtoDoc("国际机票获取配送及支付信息请")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GaGetFlightIntlPaymentAndFulfillmentResponse", namespace = "http://soa.ctrip.com/Global/API/GaGetFlightIntlPaymentAndFulfillment/v1")
@XmlType(name = "GaGetFlightIntlPaymentAndFulfillmentResponse", propOrder = {
    "responseStatus",
    "errorCode",
    "errorMsg",
    "paymentAndFulfillmentList"
})
@SuppressWarnings("all")
public class GaGetFlightIntlPaymentAndFulfillmentResponse implements HasResponseStatus {

    private static final long serialVersionUID = 1L;

    public GaGetFlightIntlPaymentAndFulfillmentResponse(
        ResponseStatusType responseStatus, 
        int errorCode, 
        String errorMsg, 
        List<PaymentAndFulfillmentModel> paymentAndFulfillmentList) {
        this.responseStatus = responseStatus;
        this.errorCode = errorCode;
        this.errorMsg = errorMsg;
        this.paymentAndFulfillmentList = paymentAndFulfillmentList;
    }

    public GaGetFlightIntlPaymentAndFulfillmentResponse() {
    }

    @FieldDoc("SOA2.0返回头部信息")
    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @FieldDoc("错误编号,0为正确")
    @JsonProperty("ErrorCode")
    @XmlElement(name = "ErrorCode")
    private int errorCode;

    @FieldDoc("错误消息,正确为空")
    @JsonProperty("ErrorMsg")
    @XmlElement(name = "ErrorMsg")
    private String errorMsg;

    @FieldDoc("可支持的配送方式及支付信息")
    @JsonProperty("PaymentAndFulfillmentList")
    @XmlElement(name = "PaymentAndFulfillmentList")
    private List<PaymentAndFulfillmentModel> paymentAndFulfillmentList;

    /**
     * SOA2.0返回头部信息
     */
    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * 错误编号,0为正确
     */
    public int getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * 错误消息,正确为空
     */
    public String getErrorMsg() {
        return this.errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * 可支持的配送方式及支付信息
     */
    public List<PaymentAndFulfillmentModel> getPaymentAndFulfillmentList() {
        return this.paymentAndFulfillmentList;
    }

    public void setPaymentAndFulfillmentList(List<PaymentAndFulfillmentModel> paymentAndFulfillmentList) {
        this.paymentAndFulfillmentList = paymentAndFulfillmentList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GaGetFlightIntlPaymentAndFulfillmentResponse other = (GaGetFlightIntlPaymentAndFulfillmentResponse)obj;
        return
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.errorCode, other.errorCode) && 
            Objects.equal(this.errorMsg, other.errorMsg) && 
            Objects.equal(this.paymentAndFulfillmentList, other.paymentAndFulfillmentList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.errorCode);
        result = 31 * result + Objects.hashCode(this.errorMsg);
        result = 31 * result + Objects.hashCode(this.paymentAndFulfillmentList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseStatus", responseStatus)
            .add("errorCode", errorCode)
            .add("errorMsg", errorMsg)
            .add("paymentAndFulfillmentList", paymentAndFulfillmentList)
            .toString();
    }
}