/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gagetflightintlpaymentandfulfillment.v1;

import com.ctrip.soa.global.api.flightcommon.v1.CityInfo;
import com.ctrip.soa.global.api.flightcommon.v1.GaDeliveryType;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 配送及支付方式实体
 */
@DtoDoc("配送及支付方式实体")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentAndFulfillmentModel", propOrder = {
    "deliveryType",
    "allowedPaymentOptionList",
    "prohibitedPaymentOptionList",
    "fulfillmentOptionList",
    "deliveryBeginTime",
    "deliveryEndTime",
    "ticketDeliveryCity"
})
@SuppressWarnings("all")
public class PaymentAndFulfillmentModel  {

    private static final long serialVersionUID = 1L;

    public PaymentAndFulfillmentModel(
        GaDeliveryType deliveryType, 
        List<PaymentWayModel> allowedPaymentOptionList, 
        List<PaymentWayModel> prohibitedPaymentOptionList, 
        List<FulfillmentOptionModel> fulfillmentOptionList, 
        String deliveryBeginTime, 
        String deliveryEndTime, 
        CityInfo ticketDeliveryCity) {
        this.deliveryType = deliveryType;
        this.allowedPaymentOptionList = allowedPaymentOptionList;
        this.prohibitedPaymentOptionList = prohibitedPaymentOptionList;
        this.fulfillmentOptionList = fulfillmentOptionList;
        this.deliveryBeginTime = deliveryBeginTime;
        this.deliveryEndTime = deliveryEndTime;
        this.ticketDeliveryCity = ticketDeliveryCity;
    }

    public PaymentAndFulfillmentModel() {
    }

    @FieldDoc("配送类型")
    @JsonProperty("DeliveryType")
    @XmlElement(name = "DeliveryType")
    private GaDeliveryType deliveryType;

    @FieldDoc("配送所对应所有可用支付列表（支付白名单）")
    @JsonProperty("AllowedPaymentOptionList")
    @XmlElement(name = "AllowedPaymentOptionList")
    private List<PaymentWayModel> allowedPaymentOptionList;

    @FieldDoc("配送所对应所有不可用支付列表（支付黑名单）")
    @JsonProperty("ProhibitedPaymentOptionList")
    @XmlElement(name = "ProhibitedPaymentOptionList")
    private List<PaymentWayModel> prohibitedPaymentOptionList;

    @FieldDoc("配送方式列表")
    @JsonProperty("FulfillmentOptionList")
    @XmlElement(name = "FulfillmentOptionList")
    private List<FulfillmentOptionModel> fulfillmentOptionList;

    @FieldDoc("HHMM	市内配送开始配送时间")
    @JsonProperty("DeliveryBeginTime")
    @XmlElement(name = "DeliveryBeginTime")
    private String deliveryBeginTime;

    @FieldDoc("HHMM	市内配送结束配送时间")
    @JsonProperty("DeliveryEndTime")
    @XmlElement(name = "DeliveryEndTime")
    private String deliveryEndTime;

    @FieldDoc("送票城市")
    @JsonProperty("TicketDeliveryCity")
    @XmlElement(name = "TicketDeliveryCity")
    private CityInfo ticketDeliveryCity;

    /**
     * 配送类型
     */
    public GaDeliveryType getDeliveryType() {
        return this.deliveryType;
    }

    public void setDeliveryType(GaDeliveryType deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * 配送所对应所有可用支付列表（支付白名单）
     */
    public List<PaymentWayModel> getAllowedPaymentOptionList() {
        return this.allowedPaymentOptionList;
    }

    public void setAllowedPaymentOptionList(List<PaymentWayModel> allowedPaymentOptionList) {
        this.allowedPaymentOptionList = allowedPaymentOptionList;
    }

    /**
     * 配送所对应所有不可用支付列表（支付黑名单）
     */
    public List<PaymentWayModel> getProhibitedPaymentOptionList() {
        return this.prohibitedPaymentOptionList;
    }

    public void setProhibitedPaymentOptionList(List<PaymentWayModel> prohibitedPaymentOptionList) {
        this.prohibitedPaymentOptionList = prohibitedPaymentOptionList;
    }

    /**
     * 配送方式列表
     */
    public List<FulfillmentOptionModel> getFulfillmentOptionList() {
        return this.fulfillmentOptionList;
    }

    public void setFulfillmentOptionList(List<FulfillmentOptionModel> fulfillmentOptionList) {
        this.fulfillmentOptionList = fulfillmentOptionList;
    }

    /**
     * HHMM市内配送开始配送时间
     */
    public String getDeliveryBeginTime() {
        return this.deliveryBeginTime;
    }

    public void setDeliveryBeginTime(String deliveryBeginTime) {
        this.deliveryBeginTime = deliveryBeginTime;
    }

    /**
     * HHMM市内配送结束配送时间
     */
    public String getDeliveryEndTime() {
        return this.deliveryEndTime;
    }

    public void setDeliveryEndTime(String deliveryEndTime) {
        this.deliveryEndTime = deliveryEndTime;
    }

    /**
     * 送票城市
     */
    public CityInfo getTicketDeliveryCity() {
        return this.ticketDeliveryCity;
    }

    public void setTicketDeliveryCity(CityInfo ticketDeliveryCity) {
        this.ticketDeliveryCity = ticketDeliveryCity;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final PaymentAndFulfillmentModel other = (PaymentAndFulfillmentModel)obj;
        return
            Objects.equal(this.deliveryType, other.deliveryType) && 
            Objects.equal(this.allowedPaymentOptionList, other.allowedPaymentOptionList) && 
            Objects.equal(this.prohibitedPaymentOptionList, other.prohibitedPaymentOptionList) && 
            Objects.equal(this.fulfillmentOptionList, other.fulfillmentOptionList) && 
            Objects.equal(this.deliveryBeginTime, other.deliveryBeginTime) && 
            Objects.equal(this.deliveryEndTime, other.deliveryEndTime) && 
            Objects.equal(this.ticketDeliveryCity, other.ticketDeliveryCity);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.deliveryType);
        result = 31 * result + Objects.hashCode(this.allowedPaymentOptionList);
        result = 31 * result + Objects.hashCode(this.prohibitedPaymentOptionList);
        result = 31 * result + Objects.hashCode(this.fulfillmentOptionList);
        result = 31 * result + Objects.hashCode(this.deliveryBeginTime);
        result = 31 * result + Objects.hashCode(this.deliveryEndTime);
        result = 31 * result + Objects.hashCode(this.ticketDeliveryCity);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("deliveryType", deliveryType)
            .add("allowedPaymentOptionList", allowedPaymentOptionList)
            .add("prohibitedPaymentOptionList", prohibitedPaymentOptionList)
            .add("fulfillmentOptionList", fulfillmentOptionList)
            .add("deliveryBeginTime", deliveryBeginTime)
            .add("deliveryEndTime", deliveryEndTime)
            .add("ticketDeliveryCity", ticketDeliveryCity)
            .toString();
    }
}