/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gaflightrevisecondition.v1;

import com.ctrip.soa.global.api.flightcommon.v1.GaPassengerType;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 人乘可退改信息
 */
@DtoDoc("人乘可退改信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PsgReviseCondition", propOrder = {
    "passengerName",
    "ticketNo",
    "ticketType",
    "ticketTypeEnum",
    "refundAble",
    "rebookAble",
    "unRebookAbleReason",
    "unRefundAbleReason",
    "insReviseConditionList",
    "refundFee",
    "cnyRefundFee",
    "refundRate",
    "feeCanCaculate",
    "airportLoungeList"
})
@SuppressWarnings("all")
public class PsgReviseCondition  {

    private static final long serialVersionUID = 1L;

    public PsgReviseCondition(
        String passengerName, 
        String ticketNo, 
        String ticketType, 
        GaPassengerType ticketTypeEnum, 
        boolean refundAble, 
        boolean rebookAble, 
        String unRebookAbleReason, 
        String unRefundAbleReason, 
        List<InsReviseCondition> insReviseConditionList, 
        BigDecimal refundFee, 
        BigDecimal cnyRefundFee, 
        float refundRate, 
        boolean feeCanCaculate, 
        List<AirportLounge> airportLoungeList) {
        this.passengerName = passengerName;
        this.ticketNo = ticketNo;
        this.ticketType = ticketType;
        this.ticketTypeEnum = ticketTypeEnum;
        this.refundAble = refundAble;
        this.rebookAble = rebookAble;
        this.unRebookAbleReason = unRebookAbleReason;
        this.unRefundAbleReason = unRefundAbleReason;
        this.insReviseConditionList = insReviseConditionList;
        this.refundFee = refundFee;
        this.cnyRefundFee = cnyRefundFee;
        this.refundRate = refundRate;
        this.feeCanCaculate = feeCanCaculate;
        this.airportLoungeList = airportLoungeList;
    }

    public PsgReviseCondition() {
    }

    @FieldDoc("乘客姓名")
    @JsonProperty("PassengerName")
    @XmlElement(name = "PassengerName")
    private String passengerName;

    @FieldDoc("票号")
    @JsonProperty("TicketNo")
    @XmlElement(name = "TicketNo")
    private String ticketNo;

    @FieldDoc("机票类型" +
            "ADU-成人" +
            "CHI-儿童" +
            "INF-婴儿")
    @JsonProperty("TicketType")
    @XmlElement(name = "TicketType")
    private String ticketType;

    @FieldDoc("票类型")
    @JsonProperty("TicketTypeEnum")
    @XmlElement(name = "TicketTypeEnum")
    private GaPassengerType ticketTypeEnum;

    @FieldDoc("是否可以提交退票")
    @JsonProperty("RefundAble")
    @XmlElement(name = "RefundAble")
    private boolean refundAble;

    @FieldDoc("是否可以提交改签")
    @JsonProperty("RebookAble")
    @XmlElement(name = "RebookAble")
    private boolean rebookAble;

    @FieldDoc("不可改原因")
    @JsonProperty("UnRebookAbleReason")
    @XmlElement(name = "UnRebookAbleReason")
    private String unRebookAbleReason;

    @FieldDoc("不可退原因")
    @JsonProperty("UnRefundAbleReason")
    @XmlElement(name = "UnRefundAbleReason")
    private String unRefundAbleReason;

    @FieldDoc("保险可退改信息")
    @JsonProperty("InsReviseConditionList")
    @XmlElement(name = "InsReviseConditionList")
    private List<InsReviseCondition> insReviseConditionList;

    @FieldDoc("退票费(支付币种)")
    @JsonProperty("RefundFee")
    @XmlElement(name = "RefundFee")
    private BigDecimal refundFee;

    @FieldDoc("退票费（人民币）")
    @JsonProperty("CNYRefundFee")
    @XmlElement(name = "CNYRefundFee")
    private BigDecimal cnyRefundFee;

    @FieldDoc("退票费率")
    @JsonProperty("RefundRate")
    @XmlElement(name = "RefundRate")
    private float refundRate;

    @FieldDoc("退票费是否可计算")
    @JsonProperty("FeeCanCaculate")
    @XmlElement(name = "FeeCanCaculate")
    private boolean feeCanCaculate;

    @FieldDoc("休息室")
    @JsonProperty("AirportLoungeList")
    @XmlElement(name = "AirportLoungeList")
    private List<AirportLounge> airportLoungeList;

    /**
     * 乘客姓名
     */
    public String getPassengerName() {
        return this.passengerName;
    }

    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    /**
     * 票号
     */
    public String getTicketNo() {
        return this.ticketNo;
    }

    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo;
    }

    /**
     * 机票类型
     *             ADU-成人
     *             CHI-儿童
     *             INF-婴儿
     */
    public String getTicketType() {
        return this.ticketType;
    }

    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }

    /**
     * 票类型
     */
    public GaPassengerType getTicketTypeEnum() {
        return this.ticketTypeEnum;
    }

    public void setTicketTypeEnum(GaPassengerType ticketTypeEnum) {
        this.ticketTypeEnum = ticketTypeEnum;
    }

    /**
     * 是否可以提交退票
     */
    public boolean getRefundAble() {
        return this.refundAble;
    }

    public void setRefundAble(boolean refundAble) {
        this.refundAble = refundAble;
    }

    /**
     * 是否可以提交改签
     */
    public boolean getRebookAble() {
        return this.rebookAble;
    }

    public void setRebookAble(boolean rebookAble) {
        this.rebookAble = rebookAble;
    }

    /**
     * 不可改原因
     */
    public String getUnRebookAbleReason() {
        return this.unRebookAbleReason;
    }

    public void setUnRebookAbleReason(String unRebookAbleReason) {
        this.unRebookAbleReason = unRebookAbleReason;
    }

    /**
     * 不可退原因
     */
    public String getUnRefundAbleReason() {
        return this.unRefundAbleReason;
    }

    public void setUnRefundAbleReason(String unRefundAbleReason) {
        this.unRefundAbleReason = unRefundAbleReason;
    }

    /**
     * 保险可退改信息
     */
    public List<InsReviseCondition> getInsReviseConditionList() {
        return this.insReviseConditionList;
    }

    public void setInsReviseConditionList(List<InsReviseCondition> insReviseConditionList) {
        this.insReviseConditionList = insReviseConditionList;
    }

    /**
     * 退票费(支付币种)
     */
    public BigDecimal getRefundFee() {
        return this.refundFee;
    }

    public void setRefundFee(BigDecimal refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * 退票费（人民币）
     */
    public BigDecimal getCnyRefundFee() {
        return this.cnyRefundFee;
    }

    public void setCnyRefundFee(BigDecimal cnyRefundFee) {
        this.cnyRefundFee = cnyRefundFee;
    }

    /**
     * 退票费率
     */
    public float getRefundRate() {
        return this.refundRate;
    }

    public void setRefundRate(float refundRate) {
        this.refundRate = refundRate;
    }

    /**
     * 退票费是否可计算
     */
    public boolean getFeeCanCaculate() {
        return this.feeCanCaculate;
    }

    public void setFeeCanCaculate(boolean feeCanCaculate) {
        this.feeCanCaculate = feeCanCaculate;
    }

    /**
     * 休息室
     */
    public List<AirportLounge> getAirportLoungeList() {
        return this.airportLoungeList;
    }

    public void setAirportLoungeList(List<AirportLounge> airportLoungeList) {
        this.airportLoungeList = airportLoungeList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final PsgReviseCondition other = (PsgReviseCondition)obj;
        return
            Objects.equal(this.passengerName, other.passengerName) && 
            Objects.equal(this.ticketNo, other.ticketNo) && 
            Objects.equal(this.ticketType, other.ticketType) && 
            Objects.equal(this.ticketTypeEnum, other.ticketTypeEnum) && 
            Objects.equal(this.refundAble, other.refundAble) && 
            Objects.equal(this.rebookAble, other.rebookAble) && 
            Objects.equal(this.unRebookAbleReason, other.unRebookAbleReason) && 
            Objects.equal(this.unRefundAbleReason, other.unRefundAbleReason) && 
            Objects.equal(this.insReviseConditionList, other.insReviseConditionList) && 
            Objects.equal(this.refundFee, other.refundFee) && 
            Objects.equal(this.cnyRefundFee, other.cnyRefundFee) && 
            Objects.equal(this.refundRate, other.refundRate) && 
            Objects.equal(this.feeCanCaculate, other.feeCanCaculate) && 
            Objects.equal(this.airportLoungeList, other.airportLoungeList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.passengerName);
        result = 31 * result + Objects.hashCode(this.ticketNo);
        result = 31 * result + Objects.hashCode(this.ticketType);
        result = 31 * result + Objects.hashCode(this.ticketTypeEnum);
        result = 31 * result + Objects.hashCode(this.refundAble);
        result = 31 * result + Objects.hashCode(this.rebookAble);
        result = 31 * result + Objects.hashCode(this.unRebookAbleReason);
        result = 31 * result + Objects.hashCode(this.unRefundAbleReason);
        result = 31 * result + Objects.hashCode(this.insReviseConditionList);
        result = 31 * result + Objects.hashCode(this.refundFee);
        result = 31 * result + Objects.hashCode(this.cnyRefundFee);
        result = 31 * result + Objects.hashCode(this.refundRate);
        result = 31 * result + Objects.hashCode(this.feeCanCaculate);
        result = 31 * result + Objects.hashCode(this.airportLoungeList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("passengerName", passengerName)
            .add("ticketNo", ticketNo)
            .add("ticketType", ticketType)
            .add("ticketTypeEnum", ticketTypeEnum)
            .add("refundAble", refundAble)
            .add("rebookAble", rebookAble)
            .add("unRebookAbleReason", unRebookAbleReason)
            .add("unRefundAbleReason", unRefundAbleReason)
            .add("insReviseConditionList", insReviseConditionList)
            .add("refundFee", refundFee)
            .add("cnyRefundFee", cnyRefundFee)
            .add("refundRate", refundRate)
            .add("feeCanCaculate", feeCanCaculate)
            .add("airportLoungeList", airportLoungeList)
            .toString();
    }
}