/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gasubmitflightintlorder.v1;

import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GaSubmitIntlFlightOrderRequestPayInfo", propOrder = {
    "cardInfoID",
    "cardTypeID",
    "payType",
    "paymentTransactionID",
    "externalNo",
    "currencyType",
    "exchangeRate",
    "amount",
    "cCardPayFee"
})
@SuppressWarnings("all")
public class GaSubmitIntlFlightOrderRequestPayInfo  {

    private static final long serialVersionUID = 1L;

    public GaSubmitIntlFlightOrderRequestPayInfo(
        int cardInfoID, 
        int cardTypeID, 
        String payType, 
        String paymentTransactionID, 
        String externalNo, 
        String currencyType, 
        float exchangeRate, 
        BigDecimal amount, 
        BigDecimal cCardPayFee) {
        this.cardInfoID = cardInfoID;
        this.cardTypeID = cardTypeID;
        this.payType = payType;
        this.paymentTransactionID = paymentTransactionID;
        this.externalNo = externalNo;
        this.currencyType = currencyType;
        this.exchangeRate = exchangeRate;
        this.amount = amount;
        this.cCardPayFee = cCardPayFee;
    }

    public GaSubmitIntlFlightOrderRequestPayInfo() {
    }

    @FieldDoc("支付Card编号")
    @JsonProperty("CardInfoID")
    @XmlElement(name = "CardInfoID")
    private int cardInfoID;

    @FieldDoc("卡种")
    @JsonProperty("CardTypeID")
    @XmlElement(name = "CardTypeID")
    private int cardTypeID;

    @FieldDoc("支付方式")
    @JsonProperty("PayType")
    @XmlElement(name = "PayType")
    private String payType;

    @FieldDoc("支付平台流水号")
    @JsonProperty("PaymentTransactionID")
    @XmlElement(name = "PaymentTransactionID")
    private String paymentTransactionID;

    @FieldDoc("支付2.0关键参数")
    @JsonProperty("ExternalNo")
    @XmlElement(name = "ExternalNo")
    private String externalNo;

    @FieldDoc("当前币种")
    @JsonProperty("CurrencyType")
    @XmlElement(name = "CurrencyType")
    private String currencyType;

    @FieldDoc("费率")
    @JsonProperty("ExchangeRate")
    @XmlElement(name = "ExchangeRate")
    private float exchangeRate;

    @FieldDoc("订单金额")
    @JsonProperty("Amount")
    @XmlElement(name = "Amount")
    private BigDecimal amount;

    @FieldDoc("外卡收付费")
    @JsonProperty("CCardPayFee")
    @XmlElement(name = "CCardPayFee")
    private BigDecimal cCardPayFee;

    /**
     * 支付Card编号
     */
    public int getCardInfoID() {
        return this.cardInfoID;
    }

    public void setCardInfoID(int cardInfoID) {
        this.cardInfoID = cardInfoID;
    }

    /**
     * 卡种
     */
    public int getCardTypeID() {
        return this.cardTypeID;
    }

    public void setCardTypeID(int cardTypeID) {
        this.cardTypeID = cardTypeID;
    }

    /**
     * 支付方式
     */
    public String getPayType() {
        return this.payType;
    }

    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * 支付平台流水号
     */
    public String getPaymentTransactionID() {
        return this.paymentTransactionID;
    }

    public void setPaymentTransactionID(String paymentTransactionID) {
        this.paymentTransactionID = paymentTransactionID;
    }

    /**
     * 支付2.0关键参数
     */
    public String getExternalNo() {
        return this.externalNo;
    }

    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo;
    }

    /**
     * 当前币种
     */
    public String getCurrencyType() {
        return this.currencyType;
    }

    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * 费率
     */
    public float getExchangeRate() {
        return this.exchangeRate;
    }

    public void setExchangeRate(float exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * 订单金额
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * 外卡收付费
     */
    public BigDecimal getCCardPayFee() {
        return this.cCardPayFee;
    }

    public void setCCardPayFee(BigDecimal cCardPayFee) {
        this.cCardPayFee = cCardPayFee;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GaSubmitIntlFlightOrderRequestPayInfo other = (GaSubmitIntlFlightOrderRequestPayInfo)obj;
        return
            Objects.equal(this.cardInfoID, other.cardInfoID) && 
            Objects.equal(this.cardTypeID, other.cardTypeID) && 
            Objects.equal(this.payType, other.payType) && 
            Objects.equal(this.paymentTransactionID, other.paymentTransactionID) && 
            Objects.equal(this.externalNo, other.externalNo) && 
            Objects.equal(this.currencyType, other.currencyType) && 
            Objects.equal(this.exchangeRate, other.exchangeRate) && 
            Objects.equal(this.amount, other.amount) && 
            Objects.equal(this.cCardPayFee, other.cCardPayFee);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.cardInfoID);
        result = 31 * result + Objects.hashCode(this.cardTypeID);
        result = 31 * result + Objects.hashCode(this.payType);
        result = 31 * result + Objects.hashCode(this.paymentTransactionID);
        result = 31 * result + Objects.hashCode(this.externalNo);
        result = 31 * result + Objects.hashCode(this.currencyType);
        result = 31 * result + Objects.hashCode(this.exchangeRate);
        result = 31 * result + Objects.hashCode(this.amount);
        result = 31 * result + Objects.hashCode(this.cCardPayFee);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("cardInfoID", cardInfoID)
            .add("cardTypeID", cardTypeID)
            .add("payType", payType)
            .add("paymentTransactionID", paymentTransactionID)
            .add("externalNo", externalNo)
            .add("currencyType", currencyType)
            .add("exchangeRate", exchangeRate)
            .add("amount", amount)
            .add("cCardPayFee", cCardPayFee)
            .toString();
    }
}