/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.pushmessage.registration.v1;

import com.ctrip.soa.global.api.comm.head.v1.Head;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "RegistrationRequest", namespace = "http://soa.ctrip.com/Global/API/PushMessage/Registration/v1")
@XmlType(name = "RegistrationRequest", propOrder = {
    "head",
    "uid",
    "deviceID",
    "updateCount",
    "timeZone"
})
@SuppressWarnings("all")
public class RegistrationRequest  {

    private static final long serialVersionUID = 1L;

    public RegistrationRequest(
        Head head, 
        String uid, 
        String deviceID, 
        Integer updateCount, 
        String timeZone) {
        this.head = head;
        this.uid = uid;
        this.deviceID = deviceID;
        this.updateCount = updateCount;
        this.timeZone = timeZone;
    }

    public RegistrationRequest() {
    }

    @JsonProperty("Head")
    @XmlElement(name = "Head")
    private Head head;

    @FieldDoc("携程UID")
    @JsonProperty("UID")
    @XmlElement(name = "UID", nillable = true)
    private String uid;

    @FieldDoc("设备ID 对应App_Device表中的DeviceID")
    @JsonProperty("DeviceID")
    @XmlElement(name = "DeviceID")
    private String deviceID;

    @FieldDoc("更新次数 最多更新两次 默认0")
    @JsonProperty("UpdateCount")
    @XmlElement(name = "UpdateCount", nillable = true)
    private Integer updateCount;

    @JsonProperty("TimeZone")
    @XmlElement(name = "TimeZone")
    private String timeZone;

    public Head getHead() {
        return this.head;
    }

    public void setHead(Head head) {
        this.head = head;
    }

    /**
     * 携程UID
     */
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * 设备ID 对应App_Device表中的DeviceID
     */
    public String getDeviceID() {
        return this.deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * 更新次数 最多更新两次 默认0
     */
    public Integer getUpdateCount() {
        return this.updateCount;
    }

    public void setUpdateCount(Integer updateCount) {
        this.updateCount = updateCount;
    }

    public String getTimeZone() {
        return this.timeZone;
    }

    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final RegistrationRequest other = (RegistrationRequest)obj;
        return
            Objects.equal(this.head, other.head) && 
            Objects.equal(this.uid, other.uid) && 
            Objects.equal(this.deviceID, other.deviceID) && 
            Objects.equal(this.updateCount, other.updateCount) && 
            Objects.equal(this.timeZone, other.timeZone);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.head);
        result = 31 * result + Objects.hashCode(this.uid);
        result = 31 * result + Objects.hashCode(this.deviceID);
        result = 31 * result + Objects.hashCode(this.updateCount);
        result = 31 * result + Objects.hashCode(this.timeZone);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("head", head)
            .add("uid", uid)
            .add("deviceID", deviceID)
            .add("updateCount", updateCount)
            .add("timeZone", timeZone)
            .toString();
    }
}