/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.payment.getpaymentneedinfo.v1;

import com.ctrip.soa.global.api.comm.head.v1.Head;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 获取可用支付方式请求
 */
@DtoDoc("获取可用支付方式请求")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GetPaymentNeedInfoRequest", namespace = "http://soa.ctrip.com/Global/API/Payment/GetPaymentNeedInfo/v1")
@XmlType(name = "GetPaymentNeedInfoRequest", propOrder = {
    "head",
    "requestType",
    "sign",
    "orderID",
    "externalNo",
    "enableTicketPay",
    "ticketType",
    "enabledPayCatalog",
    "enabledPayWay",
    "diabledPayWay",
    "isGuaranteePay",
    "enabledCardExpirationDate",
    "isNeedPreAuth"
})
@SuppressWarnings("all")
public class GetPaymentNeedInfoRequest  {

    private static final long serialVersionUID = 1L;

    public GetPaymentNeedInfoRequest(
        Head head, 
        String requestType, 
        String sign, 
        long orderID, 
        String externalNo, 
        String enableTicketPay, 
        String ticketType, 
        String enabledPayCatalog, 
        String enabledPayWay, 
        String diabledPayWay, 
        String isGuaranteePay, 
        String enabledCardExpirationDate, 
        String isNeedPreAuth) {
        this.head = head;
        this.requestType = requestType;
        this.sign = sign;
        this.orderID = orderID;
        this.externalNo = externalNo;
        this.enableTicketPay = enableTicketPay;
        this.ticketType = ticketType;
        this.enabledPayCatalog = enabledPayCatalog;
        this.enabledPayWay = enabledPayWay;
        this.diabledPayWay = diabledPayWay;
        this.isGuaranteePay = isGuaranteePay;
        this.enabledCardExpirationDate = enabledCardExpirationDate;
        this.isNeedPreAuth = isNeedPreAuth;
    }

    public GetPaymentNeedInfoRequest() {
    }

    @JsonProperty("Head")
    @XmlElement(name = "Head")
    private Head head;

    @FieldDoc("请求业务类型 0 机票 1 酒店 2国际机票 必传")
    @JsonProperty("RequestType")
    @XmlElement(name = "RequestType")
    private String requestType;

    @FieldDoc("签名 由创建订单时生成返回给客户端")
    @JsonProperty("Sign")
    @XmlElement(name = "Sign")
    private String sign;

    @FieldDoc("订单号")
    @JsonProperty("OrderID")
    @XmlElement(name = "OrderID")
    private long orderID;

    @FieldDoc("订单ExternalNo")
    @JsonProperty("ExternalNo")
    @XmlElement(name = "ExternalNo")
    private String externalNo;

    @FieldDoc("是否允许礼品卡支付 0 否 1 是")
    @JsonProperty("EnableTicketPay")
    @XmlElement(name = "EnableTicketPay")
    private String enableTicketPay;

    @FieldDoc("支持的礼品卡类型 以逗号分隔，1 任我住 2 任我游 3 任我行")
    @JsonProperty("TicketType")
    @XmlElement(name = "TicketType")
    private String ticketType;

    @FieldDoc("支持的支付类别 必传字段 如CreditCard,如果是多个则以，分隔")
    @JsonProperty("EnabledPayCatalog")
    @XmlElement(name = "EnabledPayCatalog")
    private String enabledPayCatalog;

    @FieldDoc("支付方式白名单 多个以 ,分隔")
    @JsonProperty("EnabledPayWay")
    @XmlElement(name = "EnabledPayWay")
    private String enabledPayWay;

    @FieldDoc("支付方式黑名单 多个以 ,分隔")
    @JsonProperty("DiabledPayWay")
    @XmlElement(name = "DiabledPayWay")
    private String diabledPayWay;

    @FieldDoc("是否担保支付 0 否 1 是")
    @JsonProperty("IsGuaranteePay")
    @XmlElement(name = "IsGuaranteePay")
    private String isGuaranteePay;

    @FieldDoc("信用卡有效期 截止日期 yyyyMMdd形式")
    @JsonProperty("EnabledCardExpirationDate")
    @XmlElement(name = "EnabledCardExpirationDate")
    private String enabledCardExpirationDate;

    @FieldDoc("是否预售权")
    @JsonProperty("IsNeedPreAuth")
    @XmlElement(name = "IsNeedPreAuth")
    private String isNeedPreAuth;

    public Head getHead() {
        return this.head;
    }

    public void setHead(Head head) {
        this.head = head;
    }

    /**
     * 请求业务类型 0 机票 1 酒店 2国际机票 必传
     */
    public String getRequestType() {
        return this.requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * 签名 由创建订单时生成返回给客户端
     */
    public String getSign() {
        return this.sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * 订单号
     */
    public long getOrderID() {
        return this.orderID;
    }

    public void setOrderID(long orderID) {
        this.orderID = orderID;
    }

    /**
     * 订单ExternalNo
     */
    public String getExternalNo() {
        return this.externalNo;
    }

    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo;
    }

    /**
     * 是否允许礼品卡支付 0 否 1 是
     */
    public String getEnableTicketPay() {
        return this.enableTicketPay;
    }

    public void setEnableTicketPay(String enableTicketPay) {
        this.enableTicketPay = enableTicketPay;
    }

    /**
     * 支持的礼品卡类型 以逗号分隔，1 任我住 2 任我游 3 任我行
     */
    public String getTicketType() {
        return this.ticketType;
    }

    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }

    /**
     * 支持的支付类别 必传字段 如CreditCard,如果是多个则以，分隔
     */
    public String getEnabledPayCatalog() {
        return this.enabledPayCatalog;
    }

    public void setEnabledPayCatalog(String enabledPayCatalog) {
        this.enabledPayCatalog = enabledPayCatalog;
    }

    /**
     * 支付方式白名单 多个以 ,分隔
     */
    public String getEnabledPayWay() {
        return this.enabledPayWay;
    }

    public void setEnabledPayWay(String enabledPayWay) {
        this.enabledPayWay = enabledPayWay;
    }

    /**
     * 支付方式黑名单 多个以 ,分隔
     */
    public String getDiabledPayWay() {
        return this.diabledPayWay;
    }

    public void setDiabledPayWay(String diabledPayWay) {
        this.diabledPayWay = diabledPayWay;
    }

    /**
     * 是否担保支付 0 否 1 是
     */
    public String getIsGuaranteePay() {
        return this.isGuaranteePay;
    }

    public void setIsGuaranteePay(String isGuaranteePay) {
        this.isGuaranteePay = isGuaranteePay;
    }

    /**
     * 信用卡有效期 截止日期 yyyyMMdd形式
     */
    public String getEnabledCardExpirationDate() {
        return this.enabledCardExpirationDate;
    }

    public void setEnabledCardExpirationDate(String enabledCardExpirationDate) {
        this.enabledCardExpirationDate = enabledCardExpirationDate;
    }

    /**
     * 是否预售权
     */
    public String getIsNeedPreAuth() {
        return this.isNeedPreAuth;
    }

    public void setIsNeedPreAuth(String isNeedPreAuth) {
        this.isNeedPreAuth = isNeedPreAuth;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GetPaymentNeedInfoRequest other = (GetPaymentNeedInfoRequest)obj;
        return
            Objects.equal(this.head, other.head) && 
            Objects.equal(this.requestType, other.requestType) && 
            Objects.equal(this.sign, other.sign) && 
            Objects.equal(this.orderID, other.orderID) && 
            Objects.equal(this.externalNo, other.externalNo) && 
            Objects.equal(this.enableTicketPay, other.enableTicketPay) && 
            Objects.equal(this.ticketType, other.ticketType) && 
            Objects.equal(this.enabledPayCatalog, other.enabledPayCatalog) && 
            Objects.equal(this.enabledPayWay, other.enabledPayWay) && 
            Objects.equal(this.diabledPayWay, other.diabledPayWay) && 
            Objects.equal(this.isGuaranteePay, other.isGuaranteePay) && 
            Objects.equal(this.enabledCardExpirationDate, other.enabledCardExpirationDate) && 
            Objects.equal(this.isNeedPreAuth, other.isNeedPreAuth);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.head);
        result = 31 * result + Objects.hashCode(this.requestType);
        result = 31 * result + Objects.hashCode(this.sign);
        result = 31 * result + Objects.hashCode(this.orderID);
        result = 31 * result + Objects.hashCode(this.externalNo);
        result = 31 * result + Objects.hashCode(this.enableTicketPay);
        result = 31 * result + Objects.hashCode(this.ticketType);
        result = 31 * result + Objects.hashCode(this.enabledPayCatalog);
        result = 31 * result + Objects.hashCode(this.enabledPayWay);
        result = 31 * result + Objects.hashCode(this.diabledPayWay);
        result = 31 * result + Objects.hashCode(this.isGuaranteePay);
        result = 31 * result + Objects.hashCode(this.enabledCardExpirationDate);
        result = 31 * result + Objects.hashCode(this.isNeedPreAuth);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("head", head)
            .add("requestType", requestType)
            .add("sign", sign)
            .add("orderID", orderID)
            .add("externalNo", externalNo)
            .add("enableTicketPay", enableTicketPay)
            .add("ticketType", ticketType)
            .add("enabledPayCatalog", enabledPayCatalog)
            .add("enabledPayWay", enabledPayWay)
            .add("diabledPayWay", diabledPayWay)
            .add("isGuaranteePay", isGuaranteePay)
            .add("enabledCardExpirationDate", enabledCardExpirationDate)
            .add("isNeedPreAuth", isNeedPreAuth)
            .toString();
    }
}