/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package org.tempuri.faqservice;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 获取场景值请求
 */
@DtoDoc("获取场景值请求")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GetCaseValueRequest", namespace = "http://tempuri.org/FAQService.xsd")
@XmlType(name = "GetCaseValueRequestType", propOrder = {
    "orderID",
    "uid",
    "sourceId"
})
@SuppressWarnings("all")
public class GetCaseValueRequestType  {

    private static final long serialVersionUID = 1L;

    public GetCaseValueRequestType(
        long orderID, 
        String uid, 
        String sourceId) {
        this.orderID = orderID;
        this.uid = uid;
        this.sourceId = sourceId;
    }

    public GetCaseValueRequestType() {
    }

    @FieldDoc("订单号")
    @JsonProperty("orderID")
    @XmlElement(name = "orderID")
    private long orderID;

    @FieldDoc("uid")
    @JsonProperty("uid")
    @XmlElement(name = "uid")
    private String uid;

    @FieldDoc("来源值")
    @JsonProperty("SourceId")
    @XmlElement(name = "SourceId")
    private String sourceId;

    /**
     * 订单号
     */
    public long getOrderID() {
        return this.orderID;
    }

    public void setOrderID(long orderID) {
        this.orderID = orderID;
    }

    /**
     * uid
     */
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * 来源值
     */
    public String getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GetCaseValueRequestType other = (GetCaseValueRequestType)obj;
        return
            Objects.equal(this.orderID, other.orderID) && 
            Objects.equal(this.uid, other.uid) && 
            Objects.equal(this.sourceId, other.sourceId);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.orderID);
        result = 31 * result + Objects.hashCode(this.uid);
        result = 31 * result + Objects.hashCode(this.sourceId);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("orderID", orderID)
            .add("uid", uid)
            .add("sourceId", sourceId)
            .toString();
    }
}