/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package org.tempuri.faqservice;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 获取动态答案请求
 */
@DtoDoc("获取动态答案请求")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GetDynamicAnswerRequest", namespace = "http://tempuri.org/FAQService.xsd")
@XmlType(name = "GetDynamicAnswerRequestType", propOrder = {
    "orderID",
    "uid",
    "answerKey",
    "senceId",
    "productLine"
})
@SuppressWarnings("all")
public class GetDynamicAnswerRequestType  {

    private static final long serialVersionUID = 1L;

    public GetDynamicAnswerRequestType(
        long orderID, 
        String uid, 
        String answerKey, 
        String senceId, 
        int productLine) {
        this.orderID = orderID;
        this.uid = uid;
        this.answerKey = answerKey;
        this.senceId = senceId;
        this.productLine = productLine;
    }

    public GetDynamicAnswerRequestType() {
    }

    @FieldDoc("订单号")
    @JsonProperty("orderID")
    @XmlElement(name = "orderID")
    private long orderID;

    @FieldDoc("uid")
    @JsonProperty("uid")
    @XmlElement(name = "uid")
    private String uid;

    @FieldDoc("动态答案key")
    @JsonProperty("AnswerKey")
    @XmlElement(name = "AnswerKey")
    private String answerKey;

    @FieldDoc("场景值")
    @JsonProperty("SenceId")
    @XmlElement(name = "SenceId")
    private String senceId;

    @FieldDoc("产品线")
    @JsonProperty("ProductLine")
    @XmlElement(name = "ProductLine")
    private int productLine;

    /**
     * 订单号
     */
    public long getOrderID() {
        return this.orderID;
    }

    public void setOrderID(long orderID) {
        this.orderID = orderID;
    }

    /**
     * uid
     */
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * 动态答案key
     */
    public String getAnswerKey() {
        return this.answerKey;
    }

    public void setAnswerKey(String answerKey) {
        this.answerKey = answerKey;
    }

    /**
     * 场景值
     */
    public String getSenceId() {
        return this.senceId;
    }

    public void setSenceId(String senceId) {
        this.senceId = senceId;
    }

    /**
     * 产品线
     */
    public int getProductLine() {
        return this.productLine;
    }

    public void setProductLine(int productLine) {
        this.productLine = productLine;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final GetDynamicAnswerRequestType other = (GetDynamicAnswerRequestType)obj;
        return
            Objects.equal(this.orderID, other.orderID) && 
            Objects.equal(this.uid, other.uid) && 
            Objects.equal(this.answerKey, other.answerKey) && 
            Objects.equal(this.senceId, other.senceId) && 
            Objects.equal(this.productLine, other.productLine);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.orderID);
        result = 31 * result + Objects.hashCode(this.uid);
        result = 31 * result + Objects.hashCode(this.answerKey);
        result = 31 * result + Objects.hashCode(this.senceId);
        result = 31 * result + Objects.hashCode(this.productLine);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("orderID", orderID)
            .add("uid", uid)
            .add("answerKey", answerKey)
            .add("senceId", senceId)
            .add("productLine", productLine)
            .toString();
    }
}