/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.gacreateflightorder.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 休息室预定信息
 */
@DtoDoc("休息室预定信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XProductInfo", propOrder = {
    "xid",
    "xCount",
    "ruleID",
    "printPrice"
})
@SuppressWarnings("all")
public class XProductInfo  {

    private static final long serialVersionUID = 1L;

    public XProductInfo(
        long xid, 
        int xCount, 
        long ruleID, 
        BigDecimal printPrice) {
        this.xid = xid;
        this.xCount = xCount;
        this.ruleID = ruleID;
        this.printPrice = printPrice;
    }

    public XProductInfo() {
    }

    @FieldDoc("休息室ID")
    @JsonProperty("XID")
    @XmlElement(name = "XID")
    private long xid;

    @FieldDoc("预定休息室数量")
    @JsonProperty("XCount")
    @XmlElement(name = "XCount")
    private int xCount;

    @FieldDoc("休息室政策ID")
    @JsonProperty("RuleID")
    @XmlElement(name = "RuleID")
    private long ruleID;

    @FieldDoc("预定休息室单价")
    @JsonProperty("PrintPrice")
    @XmlElement(name = "PrintPrice")
    private BigDecimal printPrice;

    /**
     * 休息室ID
     */
    public long getXid() {
        return this.xid;
    }

    public void setXid(long xid) {
        this.xid = xid;
    }

    /**
     * 预定休息室数量
     */
    public int getXCount() {
        return this.xCount;
    }

    public void setXCount(int xCount) {
        this.xCount = xCount;
    }

    /**
     * 休息室政策ID
     */
    public long getRuleID() {
        return this.ruleID;
    }

    public void setRuleID(long ruleID) {
        this.ruleID = ruleID;
    }

    /**
     * 预定休息室单价
     */
    public BigDecimal getPrintPrice() {
        return this.printPrice;
    }

    public void setPrintPrice(BigDecimal printPrice) {
        this.printPrice = printPrice;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final XProductInfo other = (XProductInfo)obj;
        return
            Objects.equal(this.xid, other.xid) && 
            Objects.equal(this.xCount, other.xCount) && 
            Objects.equal(this.ruleID, other.ruleID) && 
            Objects.equal(this.printPrice, other.printPrice);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.xid);
        result = 31 * result + Objects.hashCode(this.xCount);
        result = 31 * result + Objects.hashCode(this.ruleID);
        result = 31 * result + Objects.hashCode(this.printPrice);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("xid", xid)
            .add("xCount", xCount)
            .add("ruleID", ruleID)
            .add("printPrice", printPrice)
            .toString();
    }
}