/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.myflightstatemgr.v1;

import com.ctrip.soa.global.api.comm.head.v1.Head;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 国内机票休息室查询
 */
@DtoDoc("国内机票休息室查询")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "MyFlightStateMgrRequest", namespace = "http://soa.ctrip.com/Global/API/MyFlightStateMgr/v1")
@XmlType(name = "MyFlightStateMgrRequest", propOrder = {
    "head",
    "opType",
    "flightNo",
    "flightDate",
    "depAirportCode",
    "arrAirportCode",
    "fsid",
    "forceFollow"
})
@SuppressWarnings("all")
public class MyFlightStateMgrRequest  {

    private static final long serialVersionUID = 1L;

    public MyFlightStateMgrRequest(
        Head head, 
        int opType, 
        String flightNo, 
        long flightDate, 
        String depAirportCode, 
        String arrAirportCode, 
        int fsid, 
        boolean forceFollow) {
        this.head = head;
        this.opType = opType;
        this.flightNo = flightNo;
        this.flightDate = flightDate;
        this.depAirportCode = depAirportCode;
        this.arrAirportCode = arrAirportCode;
        this.fsid = fsid;
        this.forceFollow = forceFollow;
    }

    public MyFlightStateMgrRequest() {
    }

    @FieldDoc("SOA2.0请求头部信息")
    @JsonProperty("Head")
    @XmlElement(name = "Head")
    private Head head;

    @FieldDoc("操作类型， 1：添加关注   2:取消关注")
    @JsonProperty("OpType")
    @XmlElement(name = "OpType")
    private int opType;

    @FieldDoc("航班号")
    @JsonProperty("FlightNo")
    @XmlElement(name = "FlightNo")
    private String flightNo;

    @FieldDoc("航班日期")
    @JsonProperty("FlightDate")
    @XmlElement(name = "FlightDate")
    private long flightDate;

    @FieldDoc("出发机场三字码")
    @JsonProperty("DepAirportCode")
    @XmlElement(name = "DepAirportCode")
    private String depAirportCode;

    @FieldDoc("到达机场三字码")
    @JsonProperty("ArrAirportCode")
    @XmlElement(name = "ArrAirportCode")
    private String arrAirportCode;

    @FieldDoc("ID")
    @JsonProperty("FSID")
    @XmlElement(name = "FSID")
    private int fsid;

    @FieldDoc("强制关注")
    @JsonProperty("ForceFollow")
    @XmlElement(name = "ForceFollow")
    private boolean forceFollow;

    /**
     * SOA2.0请求头部信息
     */
    public Head getHead() {
        return this.head;
    }

    public void setHead(Head head) {
        this.head = head;
    }

    /**
     * 操作类型， 1：添加关注   2:取消关注
     */
    public int getOpType() {
        return this.opType;
    }

    public void setOpType(int opType) {
        this.opType = opType;
    }

    /**
     * 航班号
     */
    public String getFlightNo() {
        return this.flightNo;
    }

    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    /**
     * 航班日期
     */
    public long getFlightDate() {
        return this.flightDate;
    }

    public void setFlightDate(long flightDate) {
        this.flightDate = flightDate;
    }

    /**
     * 出发机场三字码
     */
    public String getDepAirportCode() {
        return this.depAirportCode;
    }

    public void setDepAirportCode(String depAirportCode) {
        this.depAirportCode = depAirportCode;
    }

    /**
     * 到达机场三字码
     */
    public String getArrAirportCode() {
        return this.arrAirportCode;
    }

    public void setArrAirportCode(String arrAirportCode) {
        this.arrAirportCode = arrAirportCode;
    }

    /**
     * ID
     */
    public int getFsid() {
        return this.fsid;
    }

    public void setFsid(int fsid) {
        this.fsid = fsid;
    }

    /**
     * 强制关注
     */
    public boolean getForceFollow() {
        return this.forceFollow;
    }

    public void setForceFollow(boolean forceFollow) {
        this.forceFollow = forceFollow;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final MyFlightStateMgrRequest other = (MyFlightStateMgrRequest)obj;
        return
            Objects.equal(this.head, other.head) && 
            Objects.equal(this.opType, other.opType) && 
            Objects.equal(this.flightNo, other.flightNo) && 
            Objects.equal(this.flightDate, other.flightDate) && 
            Objects.equal(this.depAirportCode, other.depAirportCode) && 
            Objects.equal(this.arrAirportCode, other.arrAirportCode) && 
            Objects.equal(this.fsid, other.fsid) && 
            Objects.equal(this.forceFollow, other.forceFollow);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.head);
        result = 31 * result + Objects.hashCode(this.opType);
        result = 31 * result + Objects.hashCode(this.flightNo);
        result = 31 * result + Objects.hashCode(this.flightDate);
        result = 31 * result + Objects.hashCode(this.depAirportCode);
        result = 31 * result + Objects.hashCode(this.arrAirportCode);
        result = 31 * result + Objects.hashCode(this.fsid);
        result = 31 * result + Objects.hashCode(this.forceFollow);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("head", head)
            .add("opType", opType)
            .add("flightNo", flightNo)
            .add("flightDate", flightDate)
            .add("depAirportCode", depAirportCode)
            .add("arrAirportCode", arrAirportCode)
            .add("fsid", fsid)
            .add("forceFollow", forceFollow)
            .toString();
    }
}