// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.getmyorderlist.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 订单状态
 */
@XmlType(name = "OrderOutStatus")
@XmlEnum
@SuppressWarnings("all")
public enum OrderOutStatus {

    /**
     * 全部
     */
    @XmlEnumValue("All")
    All(0, "All"),

    /**
     * 未提交
     */
    @XmlEnumValue("U")
    U(1, "U"),

    /**
     * 处理中
     */
    @XmlEnumValue("P")
    P(2, "P"),

    /**
     * 暂缓出票
     */
    @XmlEnumValue("D")
    D(3, "D"),

    /**
     * 已出票未付款
     */
    @XmlEnumValue("P8")
    P8(4, "P8"),

    /**
     * 已出票已付款
     */
    @XmlEnumValue("P40")
    P40(5, "P40"),

    /**
     * 已成交
     */
    @XmlEnumValue("S")
    S(6, "S"),

    /**
     * 部分退票
     */
    @XmlEnumValue("T")
    T(7, "T"),

    /**
     * 全部退票
     */
    @XmlEnumValue("R")
    R(8, "R"),

    /**
     * 已取消
     */
    @XmlEnumValue("C")
    C(9, "C");

    private final int intValue;
    private final String value;

    OrderOutStatus(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static OrderOutStatus fromValue(String v) {
        for (OrderOutStatus e: OrderOutStatus.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static OrderOutStatus findByValue(int value) {
        switch (value) {
            case 0:
                return All;
            case 1:
                return U;
            case 2:
                return P;
            case 3:
                return D;
            case 4:
                return P8;
            case 5:
                return P40;
            case 6:
                return S;
            case 7:
                return T;
            case 8:
                return R;
            case 9:
                return C;
            default:
                return null;
        }
    }
}