/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "http://soa.ctrip.com/Global/API/GetMyOrderList/v1", elementFormDefault = XmlNsForm.QUALIFIED)
package com.ctrip.soa.global.api.getmyorderlist.v1;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
