/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.flight.union_searchflightsws.v1;

import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightSegmentType", propOrder = {
    "origDestSeqID",
    "segmentSeqID",
    "isAddOn",
    "flightID",
    "groupID"
})
@SuppressWarnings("all")
public class FlightSegmentType  {

    private static final long serialVersionUID = 1L;

    public FlightSegmentType(
        int origDestSeqID, 
        int segmentSeqID, 
        boolean isAddOn, 
        String flightID, 
        String groupID) {
        this.origDestSeqID = origDestSeqID;
        this.segmentSeqID = segmentSeqID;
        this.isAddOn = isAddOn;
        this.flightID = flightID;
        this.groupID = groupID;
    }

    public FlightSegmentType() {
    }

    @FieldDoc("行程序号，例如，去程1，返程2")
    @JsonProperty("OrigDestSeqID")
    @XmlElement(name = "OrigDestSeqID")
    private int origDestSeqID;

    @FieldDoc("每个行程内部的航段序号")
    @JsonProperty("SegmentSeqID")
    @XmlElement(name = "SegmentSeqID")
    private int segmentSeqID;

    @FieldDoc("是否AddOn航班")
    @JsonProperty("IsAddOn")
    @XmlElement(name = "IsAddOn")
    private boolean isAddOn;

    @FieldDoc("航班信息唯一ID，用于在FlightList表查找相应航班信息")
    @JsonProperty("FlightID")
    @XmlElement(name = "FlightID")
    private String flightID;

    @FieldDoc("航班联程ID")
    @JsonProperty("GroupID")
    @XmlElement(name = "GroupID")
    private String groupID;

    /**
     * 行程序号，例如，去程1，返程2
     */
    public int getOrigDestSeqID() {
        return this.origDestSeqID;
    }

    public void setOrigDestSeqID(int origDestSeqID) {
        this.origDestSeqID = origDestSeqID;
    }

    /**
     * 每个行程内部的航段序号
     */
    public int getSegmentSeqID() {
        return this.segmentSeqID;
    }

    public void setSegmentSeqID(int segmentSeqID) {
        this.segmentSeqID = segmentSeqID;
    }

    /**
     * 是否AddOn航班
     */
    public boolean getIsAddOn() {
        return this.isAddOn;
    }

    public void setIsAddOn(boolean isAddOn) {
        this.isAddOn = isAddOn;
    }

    /**
     * 航班信息唯一ID，用于在FlightList表查找相应航班信息
     */
    public String getFlightID() {
        return this.flightID;
    }

    public void setFlightID(String flightID) {
        this.flightID = flightID;
    }

    /**
     * 航班联程ID
     */
    public String getGroupID() {
        return this.groupID;
    }

    public void setGroupID(String groupID) {
        this.groupID = groupID;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final FlightSegmentType other = (FlightSegmentType)obj;
        return
            Objects.equal(this.origDestSeqID, other.origDestSeqID) && 
            Objects.equal(this.segmentSeqID, other.segmentSeqID) && 
            Objects.equal(this.isAddOn, other.isAddOn) && 
            Objects.equal(this.flightID, other.flightID) && 
            Objects.equal(this.groupID, other.groupID);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.origDestSeqID);
        result = 31 * result + Objects.hashCode(this.segmentSeqID);
        result = 31 * result + Objects.hashCode(this.isAddOn);
        result = 31 * result + Objects.hashCode(this.flightID);
        result = 31 * result + Objects.hashCode(this.groupID);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("origDestSeqID", origDestSeqID)
            .add("segmentSeqID", segmentSeqID)
            .add("isAddOn", isAddOn)
            .add("flightID", flightID)
            .add("groupID", groupID)
            .toString();
    }
}