/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.generatecoupon.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 优惠券信息
 */
@DtoDoc("优惠券信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CouponItem", propOrder = {
    "couponID",
    "couponCode",
    "startDate",
    "endDate"
})
@SuppressWarnings("all")
public class CouponItem  {

    private static final long serialVersionUID = 1L;

    public CouponItem(
        Integer couponID, 
        String couponCode, 
        Calendar startDate, 
        Calendar endDate) {
        this.couponID = couponID;
        this.couponCode = couponCode;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public CouponItem() {
    }

    @FieldDoc("优惠券ID")
    @JsonProperty("CouponID")
    @XmlElement(name = "CouponID", nillable = true)
    private Integer couponID;

    @FieldDoc("优惠券编号")
    @JsonProperty("CouponCode")
    @XmlElement(name = "CouponCode")
    private String couponCode;

    @FieldDoc("开始时间")
    @JsonProperty("StartDate")
    @XmlElement(name = "StartDate")
    private Calendar startDate;

    @FieldDoc("结束时间")
    @JsonProperty("EndDate")
    @XmlElement(name = "EndDate")
    private Calendar endDate;

    /**
     * 优惠券ID
     */
    public Integer getCouponID() {
        return this.couponID;
    }

    public void setCouponID(Integer couponID) {
        this.couponID = couponID;
    }

    /**
     * 优惠券编号
     */
    public String getCouponCode() {
        return this.couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    /**
     * 开始时间
     */
    public Calendar getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Calendar startDate) {
        this.startDate = startDate;
    }

    /**
     * 结束时间
     */
    public Calendar getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Calendar endDate) {
        this.endDate = endDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final CouponItem other = (CouponItem)obj;
        return
            Objects.equal(this.couponID, other.couponID) && 
            Objects.equal(this.couponCode, other.couponCode) && 
            Objects.equal(this.startDate, other.startDate) && 
            Objects.equal(this.endDate, other.endDate);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.couponID);
        result = 31 * result + Objects.hashCode(this.couponCode);
        result = 31 * result + Objects.hashCode(this.startDate);
        result = 31 * result + Objects.hashCode(this.endDate);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("couponID", couponID)
            .add("couponCode", couponCode)
            .add("startDate", startDate)
            .add("endDate", endDate)
            .toString();
    }
}