/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.searchbookseat.v1;

import com.ctrip.soa.global.api.flightcommon.v1.CityInfo;
import com.ctrip.soa.global.api.flightcommon.v1.GaFlightWayType;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightHaveBookSeat", propOrder = {
    "orderID",
    "flightNo",
    "segmentNo",
    "sequence",
    "flightWay",
    "aCity",
    "dCityModel",
    "airline",
    "aPortCode",
    "dPortCode",
    "craftType",
    "clazz",
    "subClass",
    "seatNumber",
    "passengerName"
})
@SuppressWarnings("all")
public class FlightHaveBookSeat  {

    private static final long serialVersionUID = 1L;

    public FlightHaveBookSeat(
        long orderID, 
        String flightNo, 
        String segmentNo, 
        String sequence, 
        GaFlightWayType flightWay, 
        CityInfo aCity, 
        CityInfo dCityModel, 
        String airline, 
        String aPortCode, 
        String dPortCode, 
        String craftType, 
        String clazz, 
        String subClass, 
        String seatNumber, 
        String passengerName) {
        this.orderID = orderID;
        this.flightNo = flightNo;
        this.segmentNo = segmentNo;
        this.sequence = sequence;
        this.flightWay = flightWay;
        this.aCity = aCity;
        this.dCityModel = dCityModel;
        this.airline = airline;
        this.aPortCode = aPortCode;
        this.dPortCode = dPortCode;
        this.craftType = craftType;
        this.clazz = clazz;
        this.subClass = subClass;
        this.seatNumber = seatNumber;
        this.passengerName = passengerName;
    }

    public FlightHaveBookSeat() {
    }

    @FieldDoc("订单号")
    @JsonProperty("OrderID")
    @XmlElement(name = "OrderID")
    private long orderID;

    @FieldDoc("航班号")
    @JsonProperty("FlightNo")
    @XmlElement(name = "FlightNo")
    private String flightNo;

    @FieldDoc("航程号")
    @JsonProperty("SegmentNo")
    @XmlElement(name = "SegmentNo")
    private String segmentNo;

    @FieldDoc("航段号")
    @JsonProperty("Sequence")
    @XmlElement(name = "Sequence")
    private String sequence;

    @FieldDoc("航程类型")
    @JsonProperty("FlightWay")
    @XmlElement(name = "FlightWay")
    private GaFlightWayType flightWay;

    @FieldDoc("抵达城市")
    @JsonProperty("ACity")
    @XmlElement(name = "ACity")
    private CityInfo aCity;

    @FieldDoc("出发城市")
    @JsonProperty("DCityModel")
    @XmlElement(name = "DCityModel")
    private CityInfo dCityModel;

    @FieldDoc("舱空公司简称")
    @JsonProperty("Airline")
    @XmlElement(name = "Airline")
    private String airline;

    @FieldDoc("到达机场三字码")
    @JsonProperty("APortCode")
    @XmlElement(name = "APortCode")
    private String aPortCode;

    @FieldDoc("出发机场三字码")
    @JsonProperty("DPortCode")
    @XmlElement(name = "DPortCode")
    private String dPortCode;

    @FieldDoc("机型")
    @JsonProperty("CraftType")
    @XmlElement(name = "CraftType")
    private String craftType;

    @FieldDoc("大仓位")
    @JsonProperty("Class")
    @XmlElement(name = "Class")
    private String clazz;

    @FieldDoc("子仓位")
    @JsonProperty("SubClass")
    @XmlElement(name = "SubClass")
    private String subClass;

    @FieldDoc("座位号")
    @JsonProperty("SeatNumber")
    @XmlElement(name = "SeatNumber")
    private String seatNumber;

    @FieldDoc("乘客姓名")
    @JsonProperty("PassengerName")
    @XmlElement(name = "PassengerName")
    private String passengerName;

    /**
     * 订单号
     */
    public long getOrderID() {
        return this.orderID;
    }

    public void setOrderID(long orderID) {
        this.orderID = orderID;
    }

    /**
     * 航班号
     */
    public String getFlightNo() {
        return this.flightNo;
    }

    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    /**
     * 航程号
     */
    public String getSegmentNo() {
        return this.segmentNo;
    }

    public void setSegmentNo(String segmentNo) {
        this.segmentNo = segmentNo;
    }

    /**
     * 航段号
     */
    public String getSequence() {
        return this.sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    /**
     * 航程类型
     */
    public GaFlightWayType getFlightWay() {
        return this.flightWay;
    }

    public void setFlightWay(GaFlightWayType flightWay) {
        this.flightWay = flightWay;
    }

    /**
     * 抵达城市
     */
    public CityInfo getACity() {
        return this.aCity;
    }

    public void setACity(CityInfo aCity) {
        this.aCity = aCity;
    }

    /**
     * 出发城市
     */
    public CityInfo getDCityModel() {
        return this.dCityModel;
    }

    public void setDCityModel(CityInfo dCityModel) {
        this.dCityModel = dCityModel;
    }

    /**
     * 舱空公司简称
     */
    public String getAirline() {
        return this.airline;
    }

    public void setAirline(String airline) {
        this.airline = airline;
    }

    /**
     * 到达机场三字码
     */
    public String getAPortCode() {
        return this.aPortCode;
    }

    public void setAPortCode(String aPortCode) {
        this.aPortCode = aPortCode;
    }

    /**
     * 出发机场三字码
     */
    public String getDPortCode() {
        return this.dPortCode;
    }

    public void setDPortCode(String dPortCode) {
        this.dPortCode = dPortCode;
    }

    /**
     * 机型
     */
    public String getCraftType() {
        return this.craftType;
    }

    public void setCraftType(String craftType) {
        this.craftType = craftType;
    }

    /**
     * 大仓位
     */
    public String getClazz() {
        return this.clazz;
    }

    public void setClazz(String clazz) {
        this.clazz = clazz;
    }

    /**
     * 子仓位
     */
    public String getSubClass() {
        return this.subClass;
    }

    public void setSubClass(String subClass) {
        this.subClass = subClass;
    }

    /**
     * 座位号
     */
    public String getSeatNumber() {
        return this.seatNumber;
    }

    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber;
    }

    /**
     * 乘客姓名
     */
    public String getPassengerName() {
        return this.passengerName;
    }

    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final FlightHaveBookSeat other = (FlightHaveBookSeat)obj;
        return
            Objects.equal(this.orderID, other.orderID) && 
            Objects.equal(this.flightNo, other.flightNo) && 
            Objects.equal(this.segmentNo, other.segmentNo) && 
            Objects.equal(this.sequence, other.sequence) && 
            Objects.equal(this.flightWay, other.flightWay) && 
            Objects.equal(this.aCity, other.aCity) && 
            Objects.equal(this.dCityModel, other.dCityModel) && 
            Objects.equal(this.airline, other.airline) && 
            Objects.equal(this.aPortCode, other.aPortCode) && 
            Objects.equal(this.dPortCode, other.dPortCode) && 
            Objects.equal(this.craftType, other.craftType) && 
            Objects.equal(this.clazz, other.clazz) && 
            Objects.equal(this.subClass, other.subClass) && 
            Objects.equal(this.seatNumber, other.seatNumber) && 
            Objects.equal(this.passengerName, other.passengerName);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.orderID);
        result = 31 * result + Objects.hashCode(this.flightNo);
        result = 31 * result + Objects.hashCode(this.segmentNo);
        result = 31 * result + Objects.hashCode(this.sequence);
        result = 31 * result + Objects.hashCode(this.flightWay);
        result = 31 * result + Objects.hashCode(this.aCity);
        result = 31 * result + Objects.hashCode(this.dCityModel);
        result = 31 * result + Objects.hashCode(this.airline);
        result = 31 * result + Objects.hashCode(this.aPortCode);
        result = 31 * result + Objects.hashCode(this.dPortCode);
        result = 31 * result + Objects.hashCode(this.craftType);
        result = 31 * result + Objects.hashCode(this.clazz);
        result = 31 * result + Objects.hashCode(this.subClass);
        result = 31 * result + Objects.hashCode(this.seatNumber);
        result = 31 * result + Objects.hashCode(this.passengerName);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("orderID", orderID)
            .add("flightNo", flightNo)
            .add("segmentNo", segmentNo)
            .add("sequence", sequence)
            .add("flightWay", flightWay)
            .add("aCity", aCity)
            .add("dCityModel", dCityModel)
            .add("airline", airline)
            .add("aPortCode", aPortCode)
            .add("dPortCode", dPortCode)
            .add("craftType", craftType)
            .add("clazz", clazz)
            .add("subClass", subClass)
            .add("seatNumber", seatNumber)
            .add("passengerName", passengerName)
            .toString();
    }
}