/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.flightcommon.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 机票支付详细
 */
@DtoDoc("机票支付详细")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightPriceDetail", propOrder = {
    "name",
    "priceType",
    "amount",
    "copies",
    "priceOperateRule"
})
@SuppressWarnings("all")
public class FlightPriceDetail  {

    private static final long serialVersionUID = 1L;

    public FlightPriceDetail(
        String name, 
        String priceType, 
        BigDecimal amount, 
        int copies, 
        FlightPriceOperateRule priceOperateRule) {
        this.name = name;
        this.priceType = priceType;
        this.amount = amount;
        this.copies = copies;
        this.priceOperateRule = priceOperateRule;
    }

    public FlightPriceDetail() {
    }

    @FieldDoc("支付类别的名称，如：旅行险、行李额的多语言")
    @JsonProperty("Name")
    @XmlElement(name = "Name")
    private String name;

    @FieldDoc("价格类别,参照FlightCommon_v1.0.xsd 中 FlightPriceType的枚举定义类型，消费者应该不使用该字段，为API查事件使用")
    @JsonProperty("PriceType")
    @XmlElement(name = "PriceType")
    private String priceType;

    @FieldDoc("金额")
    @JsonProperty("Amount")
    @XmlElement(name = "Amount")
    private BigDecimal amount;

    @FieldDoc("份数")
    @JsonProperty("Copies")
    @XmlElement(name = "Copies")
    private int copies;

    @FieldDoc("价格运算规则")
    @JsonProperty("PriceOperateRule")
    @XmlElement(name = "PriceOperateRule")
    private FlightPriceOperateRule priceOperateRule;

    /**
     * 支付类别的名称，如：旅行险、行李额的多语言
     */
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * 价格类别,参照FlightCommon_v1.0.xsd 中 FlightPriceType的枚举定义类型，消费者应该不使用该字段，为API查事件使用
     */
    public String getPriceType() {
        return this.priceType;
    }

    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    /**
     * 金额
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * 份数
     */
    public int getCopies() {
        return this.copies;
    }

    public void setCopies(int copies) {
        this.copies = copies;
    }

    /**
     * 价格运算规则
     */
    public FlightPriceOperateRule getPriceOperateRule() {
        return this.priceOperateRule;
    }

    public void setPriceOperateRule(FlightPriceOperateRule priceOperateRule) {
        this.priceOperateRule = priceOperateRule;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final FlightPriceDetail other = (FlightPriceDetail)obj;
        return
            Objects.equal(this.name, other.name) && 
            Objects.equal(this.priceType, other.priceType) && 
            Objects.equal(this.amount, other.amount) && 
            Objects.equal(this.copies, other.copies) && 
            Objects.equal(this.priceOperateRule, other.priceOperateRule);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.name);
        result = 31 * result + Objects.hashCode(this.priceType);
        result = 31 * result + Objects.hashCode(this.amount);
        result = 31 * result + Objects.hashCode(this.copies);
        result = 31 * result + Objects.hashCode(this.priceOperateRule);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("name", name)
            .add("priceType", priceType)
            .add("amount", amount)
            .add("copies", copies)
            .add("priceOperateRule", priceOperateRule)
            .toString();
    }
}