/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.flightcommon.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 航程信息
 */
@DtoDoc("航程信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightSegment", propOrder = {
    "index",
    "departCityCode",
    "arriveCityCode",
    "departTime"
})
@SuppressWarnings("all")
public class FlightSegment  {

    private static final long serialVersionUID = 1L;

    public FlightSegment(
        int index, 
        String departCityCode, 
        String arriveCityCode, 
        String departTime) {
        this.index = index;
        this.departCityCode = departCityCode;
        this.arriveCityCode = arriveCityCode;
        this.departTime = departTime;
    }

    public FlightSegment() {
    }

    @FieldDoc("航程ID")
    @JsonProperty("Index")
    @XmlElement(name = "Index")
    private int index;

    @FieldDoc("出发城市三字码")
    @JsonProperty("DepartCityCode")
    @XmlElement(name = "DepartCityCode")
    private String departCityCode;

    @FieldDoc("到达城市三字码")
    @JsonProperty("ArriveCityCode")
    @XmlElement(name = "ArriveCityCode")
    private String arriveCityCode;

    @FieldDoc("出发时间")
    @JsonProperty("DepartTime")
    @XmlElement(name = "DepartTime")
    private String departTime;

    /**
     * 航程ID
     */
    public int getIndex() {
        return this.index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    /**
     * 出发城市三字码
     */
    public String getDepartCityCode() {
        return this.departCityCode;
    }

    public void setDepartCityCode(String departCityCode) {
        this.departCityCode = departCityCode;
    }

    /**
     * 到达城市三字码
     */
    public String getArriveCityCode() {
        return this.arriveCityCode;
    }

    public void setArriveCityCode(String arriveCityCode) {
        this.arriveCityCode = arriveCityCode;
    }

    /**
     * 出发时间
     */
    public String getDepartTime() {
        return this.departTime;
    }

    public void setDepartTime(String departTime) {
        this.departTime = departTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final FlightSegment other = (FlightSegment)obj;
        return
            Objects.equal(this.index, other.index) && 
            Objects.equal(this.departCityCode, other.departCityCode) && 
            Objects.equal(this.arriveCityCode, other.arriveCityCode) && 
            Objects.equal(this.departTime, other.departTime);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.index);
        result = 31 * result + Objects.hashCode(this.departCityCode);
        result = 31 * result + Objects.hashCode(this.arriveCityCode);
        result = 31 * result + Objects.hashCode(this.departTime);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("index", index)
            .add("departCityCode", departCityCode)
            .add("arriveCityCode", arriveCityCode)
            .add("departTime", departTime)
            .toString();
    }
}