// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.flightcommon.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 弹出消息类型
 */
@XmlType(name = "GaAlertMessageType")
@XmlEnum
@SuppressWarnings("all")
public enum GaAlertMessageType {

    /**
     * 无相关提醒（默认值）
     */
    @XmlEnumValue("Null")
    Null(0, "Null"),

    @XmlEnumValue("FirstName")
    FirstName(1, "FirstName"),

    @XmlEnumValue("MiddleName")
    MiddleName(2, "MiddleName"),

    @XmlEnumValue("LastName")
    LastName(3, "LastName"),

    @XmlEnumValue("RepeatOrder")
    RepeatOrder(4, "RepeatOrder"),

    @XmlEnumValue("Bookability")
    Bookability(5, "Bookability"),

    @XmlEnumValue("Repricing")
    Repricing(6, "Repricing");

    private final int intValue;
    private final String value;

    GaAlertMessageType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static GaAlertMessageType fromValue(String v) {
        for (GaAlertMessageType e: GaAlertMessageType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static GaAlertMessageType findByValue(int value) {
        switch (value) {
            case 0:
                return Null;
            case 1:
                return FirstName;
            case 2:
                return MiddleName;
            case 3:
                return LastName;
            case 4:
                return RepeatOrder;
            case 5:
                return Bookability;
            case 6:
                return Repricing;
            default:
                return null;
        }
    }
}