// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.flightcommon.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

@XmlType(name = "GaMailingType")
@XmlEnum
@SuppressWarnings("all")
public enum GaMailingType {

    @XmlEnumValue("EP")
    EP(0, "EP"),

    @XmlEnumValue("OM")
    OM(1, "OM"),

    @XmlEnumValue("RL")
    RL(2, "RL");

    private final int intValue;
    private final String value;

    GaMailingType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static GaMailingType fromValue(String v) {
        for (GaMailingType e: GaMailingType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static GaMailingType findByValue(int value) {
        switch (value) {
            case 0:
                return EP;
            case 1:
                return OM;
            case 2:
                return RL;
            default:
                return null;
        }
    }
}