// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.flightcommon.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 机票满仓变价检查状态(国内国际通用)
 */
@XmlType(name = "GaVerifyFlightStatus")
@XmlEnum
@SuppressWarnings("all")
public enum GaVerifyFlightStatus {

    @XmlEnumValue("Success")
    Success(0, "Success"),

    @XmlEnumValue("ParameterError")
    ParameterError(1, "ParameterError"),

    @XmlEnumValue("FullWarehouse")
    FullWarehouse(2, "FullWarehouse"),

    @XmlEnumValue("PriceChange")
    PriceChange(3, "PriceChange"),

    @XmlEnumValue("FullWarehouseAndPriceChange")
    FullWarehouseAndPriceChange(4, "FullWarehouseAndPriceChange"),

    @XmlEnumValue("FligthSearchError")
    FligthSearchError(5, "FligthSearchError"),

    @XmlEnumValue("SOACreateOrderFail")
    SOACreateOrderFail(6, "SOACreateOrderFail"),

    @XmlEnumValue("Fail")
    Fail(7, "Fail");

    private final int intValue;
    private final String value;

    GaVerifyFlightStatus(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static GaVerifyFlightStatus fromValue(String v) {
        for (GaVerifyFlightStatus e: GaVerifyFlightStatus.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static GaVerifyFlightStatus findByValue(int value) {
        switch (value) {
            case 0:
                return Success;
            case 1:
                return ParameterError;
            case 2:
                return FullWarehouse;
            case 3:
                return PriceChange;
            case 4:
                return FullWarehouseAndPriceChange;
            case 5:
                return FligthSearchError;
            case 6:
                return SOACreateOrderFail;
            case 7:
                return Fail;
            default:
                return null;
        }
    }
}