/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.flightcommon.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 定位产品的关键参数，响应中返回
 */
@DtoDoc("定位产品的关键参数，响应中返回")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductKeyInfo", propOrder = {
    "no",
    "partitionedToken",
    "nextGroupKey",
    "planCategoryName",
    "shoppingInfoID"
})
@SuppressWarnings("all")
public class ProductKeyInfo  {

    private static final long serialVersionUID = 1L;

    public ProductKeyInfo(
        Integer no, 
        String partitionedToken, 
        String nextGroupKey, 
        String planCategoryName, 
        String shoppingInfoID) {
        this.no = no;
        this.partitionedToken = partitionedToken;
        this.nextGroupKey = nextGroupKey;
        this.planCategoryName = planCategoryName;
        this.shoppingInfoID = shoppingInfoID;
    }

    public ProductKeyInfo() {
    }

    @FieldDoc("第几程航班查询")
    @JsonProperty("No")
    @XmlElement(name = "No", nillable = true)
    private Integer no;

    @FieldDoc("批次号")
    @JsonProperty("PartitionedToken")
    @XmlElement(name = "PartitionedToken", nillable = true)
    private String partitionedToken;

    @FieldDoc("航班号KEY")
    @JsonProperty("NextGroupKey")
    @XmlElement(name = "NextGroupKey")
    private String nextGroupKey;

    @FieldDoc("国际产品类型")
    @JsonProperty("PlanCategoryName")
    @XmlElement(name = "PlanCategoryName", nillable = true)
    private String planCategoryName;

    @FieldDoc("PU为一键")
    @JsonProperty("ShoppingInfoID")
    @XmlElement(name = "ShoppingInfoID", nillable = true)
    private String shoppingInfoID;

    /**
     * 第几程航班查询
     */
    public Integer getNo() {
        return this.no;
    }

    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * 批次号
     */
    public String getPartitionedToken() {
        return this.partitionedToken;
    }

    public void setPartitionedToken(String partitionedToken) {
        this.partitionedToken = partitionedToken;
    }

    /**
     * 航班号KEY
     */
    public String getNextGroupKey() {
        return this.nextGroupKey;
    }

    public void setNextGroupKey(String nextGroupKey) {
        this.nextGroupKey = nextGroupKey;
    }

    /**
     * 国际产品类型
     */
    public String getPlanCategoryName() {
        return this.planCategoryName;
    }

    public void setPlanCategoryName(String planCategoryName) {
        this.planCategoryName = planCategoryName;
    }

    /**
     * PU为一键
     */
    public String getShoppingInfoID() {
        return this.shoppingInfoID;
    }

    public void setShoppingInfoID(String shoppingInfoID) {
        this.shoppingInfoID = shoppingInfoID;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ProductKeyInfo other = (ProductKeyInfo)obj;
        return
            Objects.equal(this.no, other.no) && 
            Objects.equal(this.partitionedToken, other.partitionedToken) && 
            Objects.equal(this.nextGroupKey, other.nextGroupKey) && 
            Objects.equal(this.planCategoryName, other.planCategoryName) && 
            Objects.equal(this.shoppingInfoID, other.shoppingInfoID);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.no);
        result = 31 * result + Objects.hashCode(this.partitionedToken);
        result = 31 * result + Objects.hashCode(this.nextGroupKey);
        result = 31 * result + Objects.hashCode(this.planCategoryName);
        result = 31 * result + Objects.hashCode(this.shoppingInfoID);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("no", no)
            .add("partitionedToken", partitionedToken)
            .add("nextGroupKey", nextGroupKey)
            .add("planCategoryName", planCategoryName)
            .add("shoppingInfoID", shoppingInfoID)
            .toString();
    }
}