/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.global.api.flightcommon.v1;

import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 改签人信息
 */
@DtoDoc("改签人信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RQPassengerInfo", propOrder = {
    "name",
    "ticketNumber"
})
@SuppressWarnings("all")
public class RQPassengerInfo  {

    private static final long serialVersionUID = 1L;

    public RQPassengerInfo(
        String name, 
        String ticketNumber) {
        this.name = name;
        this.ticketNumber = ticketNumber;
    }

    public RQPassengerInfo() {
    }

    @FieldDoc("姓名")
    @JsonProperty("Name")
    @XmlElement(name = "Name")
    private String name;

    @FieldDoc("票号")
    @JsonProperty("TicketNumber")
    @XmlElement(name = "TicketNumber")
    private String ticketNumber;

    /**
     * 姓名
     */
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * 票号
     */
    public String getTicketNumber() {
        return this.ticketNumber;
    }

    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final RQPassengerInfo other = (RQPassengerInfo)obj;
        return
            Objects.equal(this.name, other.name) && 
            Objects.equal(this.ticketNumber, other.ticketNumber);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.name);
        result = 31 * result + Objects.hashCode(this.ticketNumber);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("name", name)
            .add("ticketNumber", ticketNumber)
            .toString();
    }
}