/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "", elementFormDefault = XmlNsForm.QUALIFIED)
package com.ctrip.soa.global.api.flightsonlinepaymentnotify.v1;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
